### ISSUE TITLE
Install failure, any ideas?

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#1003]
My wife was trying to install ubuntu 20.04.  From searching online, this seems to be potentially something not specifically related to k2, but maybe related to python versions?  It seems like something maybe doesn't want  glibc==2.31, but I don't see anything in the k2 repo about that.
```
conda install -c k2-fsa k2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

**Comment by csukuangfj** [comment]
How about also specifying the python version during installation? That is, use
```bash
conda install -c k2-fsa k2 python=3.8
```

Also, the [recommended installation instruction](https://k2-fsa.github.io/k2/installation/conda.html)
is to also specify the version of PyTorch and cuda
```
$ conda install -c k2-fsa -c pytorch -c conda-forge k2 python=3.8 cudatoolkit=11.1 pytorch=1.8.1
```

You can choose which version of python, cudatoolkit and pytorch to install.

**Comment by danpovey** [comment]
Yes, it just started spinning for a long time trying to find the right version, so i installed PyTorch and the cuda toolkit manually.

**Comment by csukuangfj** [comment]
You can find all available versions of pytorch, python, and cudatoolkit by visiting
https://anaconda.org/k2-fsa/k2/files

**Comment by danpovey** [comment]
OK, cool.  Suppose I manage to install compatible right version of Python, pytorch and the CUDA toolkit, is there a way to tell conda which version of k2 to use?  E.g. if it is looking in the wrong place for the cuda toolkit version or something?

**Comment by csukuangfj** [comment]
Suppose you want to install the following version marked with a red rectangle. You can use
```
$ conda install -c k2-fsa -c pytorch -c conda-forge k2=1.17.dev20220704  python=3.8 cudatoolkit=11.3 pytorch=1.12.0
```
![c0a2](https://user-images.githubusercontent.com/5284924/177243586-0ec8650e-c9dd-4261-848c-03d5321c0ba5.png)

**Comment by danpovey** [comment]
yeah but what if I have already installed the cuda toolkit via the system installer and don't want to install through conda?

**Comment by csukuangfj** [comment]
> yeah but what if I have already installed the cuda toolkit via the system installer and don't want to install through conda?

I don't know if it is possible to let conda use your already installed system CUDA that is not managed by conda.

To me, if you want to install a package with conda, conda also installs all of its dependencies.

Some people like this since conda does everything for them.

 However, I prefer to install packages and manages all dependencies by myself.

**Comment by csukuangfj** [comment]
> yeah but what if I have already installed the cuda toolkit via the system installer and don't want to install through conda?]

I recommend you to install k2 from source if you managed to install PyTorch and cudatoolkit by yourself.

See https://k2-fsa.github.io/k2/installation/from_source.html
