### ISSUE TITLE
ImportError: No module named '_k2'

### ISSUE THREAD

**Issue by xrick** [k2-fsa/k2#1011]
I have installed k2 on ubuntu 16.04. But I encounter import errors:
on ubuntu:
Traceback (most recent call last):
  File "/home/xrick/miniconda3/envs/k2env/lib/python3.8/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xrick/miniconda3/envs/k2env/lib/python3.8/site-packages/k2/__init__.py", line 30, in <module>
    raise ImportError(
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH
What causes the problem???

**Comment by csukuangfj** [comment]
Can you find the missing lib in /home/xrick/miniconda3/envs ?

**Comment by csukuangfj** [comment]
What is the output of
```bash
find /home/xrick/miniconda3 -name "libpython*"
```

**Comment by xrick** [comment]
@csukuangfj 
the output of the find command is 
/home/xrick/miniconda3/envs/venv/lib/libpython3.9.so
/home/xrick/miniconda3/envs/venv/lib/libpython3.so
/home/xrick/miniconda3/envs/venv/lib/libpython3.9.so.1.0
/home/xrick/miniconda3/pkgs/python-3.9.7-h12debd9_1/lib/libpython3.9.so
/home/xrick/miniconda3/pkgs/python-3.9.7-h12debd9_1/lib/libpython3.so
/home/xrick/miniconda3/pkgs/python-3.9.7-h12debd9_1/lib/libpython3.9.so.1.0
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_1/lib/libpython3.9.so
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_1/lib/libpython3.so
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_1/lib/libpython3.9.so.1.0
/home/xrick/miniconda3/pkgs/python-3.8.0-h0371630_2/lib/libpython3.8.a
/home/xrick/miniconda3/pkgs/python-3.8.0-h0371630_2/lib/libpython3.8.so.1.0
/home/xrick/miniconda3/pkgs/python-3.8.0-h0371630_2/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.a
/home/xrick/miniconda3/pkgs/python-3.8.0-h0371630_2/lib/libpython3.8.so.1
/home/xrick/miniconda3/pkgs/python-3.8.0-h0371630_2/lib/libpython3.8.so
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_0/lib/libpython3.9.so
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_0/lib/libpython3.so
/home/xrick/miniconda3/pkgs/python-3.9.12-h12debd9_0/lib/libpython3.9.so.1.0
/home/xrick/miniconda3/pkgs/python-3.8.13-h12debd9_0/lib/libpython3.8.so.1.0
/home/xrick/miniconda3/pkgs/python-3.8.13-h12debd9_0/lib/libpython3.so
/home/xrick/miniconda3/pkgs/python-3.8.13-h12debd9_0/lib/libpython3.8.so
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/libpython3.7m.so.1.0
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/libpython3.7m.so
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/libpython3.7m.nolto.a
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/libpython3.so
/home/xrick/miniconda3/pkgs/python-3.7.13-h12debd9_0/lib/libpython3.7m.a
/home/xrick/miniconda3/lib/libpython3.9.so
/home/xrick/miniconda3/lib/libpython3.so
/home/xrick/miniconda3/lib/libpython3.9.so.1.0
libpython3.8.so does exist, but does it in correct path?

**Comment by csukuangfj** [comment]
@xrick 

The fix is
```
export LD_LIBRARY_PATH=/home/xrick/miniconda3/pkgs/python-3.8.13-h12debd9_0/lib:$LD_LIBRARY_PATH
```

**Comment by csukuangfj** [comment]
> I encountered the same problem, did you solve it?

@JiawangLiu 

Could you try the above approach?

**Comment by JiawangLiu** [comment]
> > I encountered the same problem, did you solve it?
> 
> @JiawangLiu
> 
> Could you try the above approach?

Yes, it worked! But another problem has arisen when I run `egs/yesno/ASR/prepare.sh`

`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found`

I install k2 on `pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel` docker and the installation command is `pip install https://huggingface.co/csukuangfj/k2/resolve/main/cuda/k2-1.24.3.dev20230524+cuda11.7.torch2.0.0-cp39-cp39-linux_x86_64.whl`

**Comment by csukuangfj** [comment]
The k2 pre-compiled wheel is built on Ubuntu 20.04.

Please install k2 from source in your case.

**Comment by JiawangLiu** [comment]
> The k2 pre-compiled wheel is built on Ubuntu 20.04.
> 
> Please install k2 from source in your case.

When I install k2 from source I encounter another problem when I run `egs/yesno/ASR/prepare.sh`
```
from _k2 import DeterminizeWeightPushingType
ImportError: libk2context.so: cannot open shared object file: No such file or directory
```
The `python3 -m torch.utils.collect_env` command output:
```
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 21:04:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.14.0_1-0-0-47-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.99
...
Nvidia driver version: 460.27.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.24.3.dev20230707+cuda11.7.torch1.13.0
[pip3] numpy==1.22.4
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[conda] blas                      1.0                         mkl  
[conda] k2                        1.24.3.dev20230707+cuda11.7.torch1.13.0          pypi_0    pypi
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.13.0          py3.8_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.0                   pypi_0    pypi
```

**Comment by csukuangfj** [comment]
@JiawangLiu 

The reason is that you have multiple versions of k2 installed in your current environment.

The fix is to remove the previously installed k2.

**Comment by JiawangLiu** [comment]
But I only find one when I run `pip uninstall k2`

```
Found existing installation: k2 1.24.3.dev20230707+cuda11.7.torch1.13.0
Uninstalling k2-1.24.3.dev20230707+cuda11.7.torch1.13.0:
  Would remove:
    /opt/conda/envs/k2v6/lib/python3.8/site-packages/k2-1.24.3.dev20230707+cuda11.7.torch1.13.0-py3.8-linux-x86_64.egg
Proceed (Y/n)?
```

**Comment by csukuangfj** [comment]
![Screenshot 2023-07-08 at 13 27 02](https://github.com/k2-fsa/k2/assets/5284924/a0dc0411-cd5e-4f95-9fd5-78ac99c9ffe1)


Please use
```
find /opt/conda -name _k2.cpython-38-x86_64-linux-gnu.so
```

to find the above file and remove it.
(You should find two files and you can compare their creation time and remove the old one)

**Comment by csukuangfj** [comment]
If you only find one file, please post the absolute path of it and run
```
readelf -d _k2.cpython-38-x86_64-linux-gnu.so
```
and please show the output.

**Comment by JiawangLiu** [comment]
Yes, I find two files. After delete old one, it runs successfully! Thank you very much!

**Comment by anci123** [comment]
I've also encountered this problem.
I tried the solution of exporting the library path, but the problem still exists.
```
export LD_LIBRARY_PATH=/share/nas169/ancipeng/miniconda3/pkgs/python-3.12.8-h5148396_0/lib:$LD_LIBRARY
_PATH
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages/k2/__init__.py", line 2, in <module>
    from _k2 import RaggedInt  # TODO(fangjun): move it to k2.ragged
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_k2'
```

**Comment by csukuangfj** [comment]
can you describe how you install k2 and post installation logs?

**Comment by anci123** [comment]
I used pip to install k2, here's the installation logs.

```
pip install k2
Requirement already satisfied: k2 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (0.3.0)
Requirement already satisfied: torch in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from k2) (2.7.1)
Requirement already satisfied: graphviz in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from k2) (0.21)
Requirement already satisfied: filelock in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (4.12.2)
Requirement already satisfied: setuptools in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (75.8.0)
Requirement already satisfied: sympy>=1.13.3 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (1.14.0)
Requirement already satisfied: networkx in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (3.5)
Requirement already satisfied: jinja2 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (3.1.6)
Requirement already satisfied: fsspec in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from torch->k2) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch->k2) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /share/nas169/ancipeng/miniconda3/lib/python3.12/site-packages (from jinja2->torch->k2) (3.0.2)
```

**Comment by csukuangfj** [comment]
Please follow our doc to install k2.

Your approach is not correct.

**Comment by anci123** [comment]
Thanks for your advice. I followed the doc to reinstall, the error did not appear again.
