### ISSUE TITLE
Renaming of Automatically Numbered Aux Labels 

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/k2#1015]
I'm trying on a method where multiple aux labels are associated with an arc, and in order to preserve flexibility, I have to use the automatically numbered format, i.e. "aux_labels", "aux_labels2", "aux_labels3", as defined in [get_aux_label_info](https://github.com/k2-fsa/k2/blob/6ccbe9c28f69aa3d897a4bedc7d879fe0ec7f5f3/k2/python/k2/fsa.py#L1427) . 

However, when renaming aux_labels -> xxx so that I can do aux_labels2 -> aux_labels, I find that aux_labels2 gets renamed too to xxx2. For now, I just delete aux_labels prior to moving aux_labels2 -> aux_labels, but I was thinking that since my numbered aux labels are automatically generated, they should not trip over another method. 

It seems that adding `src_name += '_'` should solve this. 

[rename_tensor_attribute_](https://github.com/k2-fsa/k2/blob/6ccbe9c28f69aa3d897a4bedc7d879fe0ec7f5f3/k2/python/k2/fsa.py#L894)
```
        src_name += '_'
        src_name_len = len(src_name)
        dest_name_len = len(dest_name)
        to_move = []
        for name, value in list(self._non_tensor_attr.items()):
            if name[:src_name_len] == src_name:
                # remove src_name from prefix and replace with dest_name
                new_name = dest_name + name[src_name_len:]
                to_move.append((name, new_name, value))
            elif name[:dest_name_len] == dest_name:
                del self._non_tensor_attr[name]
```

On the other hand, are there any thoughts to expose the aux_labels choice to users, in methods like `k2.invert` and `k2.compose`? They could definitely default back to 'aux_labels', thus theoretically not impacting existing codes. 

I understand that the use case for multiple aux_labels might not be as frequent, but an interesting aspect of k2 for me is the flexibility of output labels. 

Environment information as below:

> Collecting environment information...
> 
> k2 version: 1.15.1
> Build type: Release
> Git SHA1: 350e449fe5d7b4231f77eb0add764782eed9f5d2
> Git date: Thu May 26 14:56:24 2022
> Cuda used to build k2: 11.0
> cuDNN used to build k2: 8.0.4
> Python version used to build k2: 3.8
> OS used to build k2: 
> CMake version: 3.18.0
> GCC version: 7.5.0
> CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
> CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
> PyTorch version used to build k2: 1.7.1
> PyTorch is using Cuda: 11.0
> NVTX enabled: True
> With CUDA: True
> Disable debug: True
> Sync kernels : False
> Disable checks: False
> Max cpu memory allocate: 214748364800
> k2 abort: False

**Comment by pkufool** [comment]
Can you show me your code? I think the following lines might work:
```
fsa.xxx = fsa.aux_labels
fsa.aux_labels = fsa.aux_labels2
```
From your description, I suspect that your aux_labels2 is not a tensor attribute.

We will rename all non_tensor attributes with the same prefix of the renamed tensor attributes, because there will be hidden non-tensor attributes associating the tensor attributes by sharing prefix, like filler.
https://github.com/k2-fsa/k2/blob/5954046db8b1305072c5f55914061b6ec87d4622/k2/python/k2/fsa.py#L306-L330

**Comment by teowenshen** [comment]
Thank you for your comments. 

Indeed I was mistaken. In my case, it was the SymbolTable associated with the aux_labels that was incorrectly renamed. The aux_labels themselves were renamed as expected. 

In my sample code below, I am attempting to rename `aux_labels` to `new_name`, while `aux_labels2` should remain as is. This accidentally caused aux_labels2_sym to be renamed to new_name2_sym as well. 

```
import k2 
sample_str = """0 1 1 10 100 0
0 2 2 20 200 0
1 2 0 30 300 0
2 3 -1 -1 -1 0
3
"""

labels_sym_str = """label_1 1
label_2 2
"""

aux_labels_sym_str = """aux_labels_1 10
aux_labels_2 20
aux_labels_3 30
"""

aux_labels2_sym_str = """aux_labels2_1 100
aux_labels2_2 200
aux_labels2_3 300
"""
fst = k2.Fsa.from_str(sample_str, num_aux_labels=2)
fst.labels_sym = k2.SymbolTable.from_str(labels_sym_str)
fst.aux_labels_sym = k2.SymbolTable.from_str(aux_labels_sym_str)
fst.aux_labels2_sym = k2.SymbolTable.from_str(aux_labels2_sym_str)
print("Before remove epsilon")
print(fst.to_str())
fst = k2.remove_epsilon(fst)
print("After remove epsilon")
print(fst.to_str())
fst.rename_tensor_attribute_('aux_labels', 'new_name')
print(fst.to_str())
```

I guess I am still quite early in the development of my experiment, which is why the SymbolTables are still important for debugging. Maybe once everything is stable I will use your method of assigning the labels directly. 

I just tried this, and it works. 
```fst.aux_labels, fst.aux_labels2 = fst.aux_labels2, fst.aux_labels```
