### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/k2#1027]
I installed k2 from [source](https://k2-fsa.github.io/k2/installation/from_source.html), and the installation process is successful. But when i import k2, it came out the following error:

```
python3 -c "import k2; print(k2.__file__)"
Traceback (most recent call last):
  File "/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/k2-1.17.dev20220801+cuda10.2.torch1.10.1-py3.8-linux-x86_64.egg/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/k2-1.17.dev20220801+cuda10.2.torch1.10.1-py3.8-linux-x86_64.egg/k2/__init__.py", line 30, in <module>
    raise ImportError(
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH

```

**Comment by csukuangfj** [comment]
What is your os version, glibc version, torch version, GCC version, cuda version ?

**Comment by PPGGG** [comment]
> What is your os version, glibc version, torch version, GCC version, cuda version ?

- os version: Centos 7
- glibc version: 
```
$ ldd --version
ldd (GNU libc) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
- torch version : V1.10.1
- GCC version: 8.3.1
- CUDA version : 10.2

**Comment by csukuangfj** [comment]
Have you installed k2 previously? If yes, how did you uninstall it?

Could you show the output of the following commands:
```bash
ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/k2-1.17.dev20220801+cuda10.2.torch1.10.1-py3.8-linux-x86_64.egg/*.so

ls -lh /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so
```

**Comment by PPGGG** [comment]
1. I tried to create a new environment and reinstall k2 
2. 
- the output of `ls -lh` is below:
`-rwxr-xr-x 1 Dell Dell 16M Aug  1 12:22 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/k2-1.17.dev20220801+cuda10.2.torch1.10.1-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so`

- the output of `ls -lh` is below:
`-rw-rw-r-- 1 Dell Dell 78M Aug  1 11:24 /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so`

**Comment by csukuangfj** [comment]
Please delete
```
/home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so
```

The above file was installed by `conda install`, I guess.

**Comment by PPGGG** [comment]
> Please delete
> 
> ```
> /home/Dell/anaconda3/envs/streaming_asr/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so
> ```
> 
> The above file was installed by `conda install`, I guess.

After re-create environment, and git clone k2 again and using `python setup.py install`, Finally it worked out.
