### ISSUE TITLE
blank token in FSA

### ISSUE THREAD

**Issue by ncakhoa** [k2-fsa/k2#1067]
I tried to modify pruned_stateless_emformer_rnnt2 (https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_stateless_emformer_rnnt2) model for training with phonemes instead of bpe. But in the decoding phase, it had some bugs in FSA LG.pt. When I was tracking, I realized that the ID of \<blk\> token in the bpe tokens list always is 0, so I wonder: Is 0 set as the default ID value of \<blk\> when building LG FSA?

**Comment by pkufool** [comment]
Yes, blank id is always 0 in fast_beam_search.
