### ISSUE TITLE
Extra arcs with a score of 0 in the lattice?

### ISSUE THREAD

**Issue by francisr** [k2-fsa/k2#1092]
I'm doing a decode with a trivial graph, and here are the first states of the lattice I get:
```
FsaVec[0]: 0 1 0 0 -0.093668
0 3 5 5 -4.1686
0 4 7 7 -3.16219
0 5 19 19 -1.64128
0 6 34 34 -2.40031
0 7 54 54 -5.32528
0 8 128 128 -5.06403
0 9 169 169 -4.97348
0 2 0 0 0
1 10 0 0 -0.0347466
1 12 5 5 -5.21351
1 14 7 7 -4.67426
1 16 19 19 -3.03204
1 18 34 34 -3.40623
1 11 0 0 0
2 11 0 0 -0.0347466
3 12 0 0 -0.00258392
3 13 0 0 0
4 14 0 0 -0.000933422
4 15 0 0 0
5 16 0 0 -0.000155441
5 17 0 0 0
6 18 0 0 -1.06483
6 20 2 2 -1.16635
6 21 28 28 -1.20667
6 22 326 326 -1.45139
6 19 0 0 0
```
I can see that most states have 2 blank arcs, with the second one having a score of 0. Where does that come from?

**Comment by glynpu** [comment]
Actually, it's the arc with label == -1.
Here is a lattice with 20 frames input. There are two arcs with label ==0, but one stopped to expand.
For these stopped expanded arcs, during decoding, their labels are -1, while during `FormatOutput` lattice, these labels are manually set to 0.  
<img width="830" alt="image" src="https://user-images.githubusercontent.com/14951566/200094511-5638fb63-20c9-4494-a445-b075c95c1b32.png">

Code for during decoding:
https://github.com/k2-fsa/k2/blob/9b0763930ea9d773c14462992157b75878d0f187/k2/csrc/rnnt_decode.cu#L320

Set to 0 during `FormatOutput` lattice:
https://github.com/k2-fsa/k2/blob/9b0763930ea9d773c14462992157b75878d0f187/k2/csrc/rnnt_decode.cu#L877-L883

**Comment by glynpu** [comment]
BTW, I noticed in your lattice, both of two arcs with arc.label = -1 continue to expand.
Some selected rows from your lattice
```
FsaVec[0]: 0 1 0 0 -0.093668
0 2 0 0 0
1 10 0 0 -0.0347466
1 11 0 0 0
2 11 0 0 -0.0347466
```

State 2 should stop to expand since it's an arc with label==-1. 
While there is an arc `2 11 0 0 -0.0347466` !
We already fix this with this pr https://github.com/k2-fsa/k2/pull/1083/files

Maybe your are not using the latest k2.

**Comment by francisr** [comment]
Thanks for the explanation!
