### ISSUE TITLE
Revise the lattice before forward-backward

### ISSUE THREAD

**Issue by jctian98** [k2-fsa/k2#1095]
Hello!
I wonder if there is a way to revise the lattice before conducting the forward-backward process.

Specifically: 
1) I get a lattice: `lats = k2.intersect_dense(graph, dense_fsa_vec)`;
2) What I want to do is to prune some specific arcs or set the weights attached to these arcs to some very small values. To specify which arcs to prune, I have a bool `mask` with the length of `lats.num_arcs`
3) Then, I'd like to get the scores through the `get_tot_scores, get_forward_scores, get_backward_scores` APIs. So it would be good if we can keep the differentiability through this process (to get the gradient for the `dense_fsa_vec`).

Thanks a lot! :)

**Comment by csukuangfj** [comment]
How about 

"""
lats.scores = lats.scores * mask
"""

**Comment by jctian98** [comment]
Thanks! That solves the question. Didn't see the `.scores` API.
