### ISSUE TITLE
Wrong forward and backward scores when an arc weight is changed

### ISSUE THREAD

**Issue by jctian98** [k2-fsa/k2#1104]
Hi! I'm trying to modify the weight on a certain arc. But after that, the forward-backward scores seem not correct.

The code is:
```
print('idx: ', zero_idx)
lats.scores[zero_idx] = 0.0
print('scores: ', lats.scores)
lats[0].draw('lat.png')
bw_scores = lats.get_backward_scores(True, True)
fw_scores = lats.get_forward_scores(True, True)
print("backward_scores: " , bw_scores)
print("forward_scores:", fw_scores)
```

The `lats` has only one FSA and looks like below. The arc with the index of 6 is to modify: `idx:  tensor([6], device='cuda:0')`.
![rnnt_lat](https://user-images.githubusercontent.com/92212251/201662081-ccb0a93e-f7c1-4a50-b595-ce2e9a060d09.png)

The scores have been changed:
`scores:  tensor([-1.441691, -1.249144, -1.893759, -1.694620, -1.370999, -1.370999,
         0.000000], device='cuda:0')`

But the forward and backward scores suggest the weight on the last arc has NOT been changed. (the last-second backward score is not 0).
```
backward_scores:  tensor([-5.169402, -4.635757, -4.436618, -2.741998, -2.741998, -1.370999,
         0.000000], device='cuda:0', dtype=torch.float64)
forward_scores: tensor([ 0.000000, -1.441691, -1.249144, -3.335450, -2.943764, -3.798403,
        -5.169402], device='cuda:0', dtype=torch.float64)
```

The K2 version is 1.16.

Thanks a lot!

**Comment by csukuangfj** [comment]
```
lats[0].draw('lat.png')
```
So your `lats` is an FsaVec, which means `lats.scores` and `lats.arcs.values()[:, 3]` are two different things.

In general, if you assign a value to `lats.scores`, it will also update `lats.arcs.values()[:, 3]`.
That is, if you do
```
lats.scores = some_tensor
```
then `lats.arcs.values()[:, 3]` is also updated.

`lats.scores = some_tensor` invokes `__setattr__` of an `Fsa`, where we also update `lats.arcs.values()[:, 3]`.

But this is not the case when you use `lats.scores[some_index] = some_value`.

`lats.scores` invokes `__getattr__` and it is not possible to know tell when it should update `lats.arcs.values()[:, 3]`.

---
```
lats[0].draw('lat.png')
```

`lats[0]` is a new Fsa, whose `arcs.values()` is from `lats.arcs.values()` and `lats.scores` only participate
in gradient propagation.

---

If you do

```python3
scores = lats.scores
scores[zero_idx] = 0
lats.scores = scores
```

then everything should work as expected.

---

It is not possible for us to fix such an issue, I am afraid.
