### ISSUE TITLE
What are differences between nbest in icefall and k2

### ISSUE THREAD

**Issue by ncakhoa** [k2-fsa/k2#1119]
Hi, I see nbest class is written on both icefall and k2 libraries. So what are the differences between two versions of nbest, and what is the main version, can I use either of them?

**Comment by csukuangfj** [comment]
>  can I use either of them?

Yes, I think so.

If you compare the source code of them, they are basically the same. Not sure why there are two copies.

**Comment by glynpu** [comment]
@ncakhoa  Differences:
1. The main difference is  k2.nbest support autograd,  while the one in icefall doesn't.
2. nebst in icefall may have more functions related to decoding
3. k2.nbest is mainly used by k2.mwer, a Loss function.
