### ISSUE TITLE
Rethinking some API isn't generalizing.

### ISSUE THREAD

**Issue by dthtuenguyen** [k2-fsa/k2#1130]
In k2, all the decoding methods with graph intersection based on state_less decoder.
For example: In RNN-T decoding, the api push information from previous step of RNNT-decoding by decoding.get_context() return the history_len of context before. 
I think we should change it. 
decoding.get_context() should return something can get:
1. The list of context 
2. Where it come from ( batch_idx,...)
3. For each context, we just need:
  - Last token of context
  - Where context come from previous
 For example:
step 1: 
get_context(): -> shape: - infor of batch_idx | context (1,2) : context[0][0] = 0  context[0][1]=0 
forward() + advance()
step 2:
get_context() : -> shape: - infor of batch_idx| context(m,2): context[0][0]=0, context[0][1]=2, context[1][0]=0,context[1][1]=3
forward() + advance()
step 3:
get_context(): -> shape: - infor of batch_idx| context(m,2): context[0][0]=1 ( come from context[1] in step 2 -> history_token_before= 3) context[0][1]=4 -> history = [3,4]
.....
We can keep infinte history_decoder and it can support LSTM decoder.
I think about it and also try to understand the k2/c++ code but can do anything to modified it.
-----------------
Also for the RNN-T decoding support LSTM decoder.
In the python level I have the idea:
step: decoding 1: save string (max-score)
step: decoding 2: convert string previous  + output of model decoding (Vocab_size) to the graph and intersect it with LG graph to get the top_k path max-score.
Step decoding 3: for all string in top_k in step 2, I convert it  + output of model decoding to the graph and intersect it with LG to get the top_k path max-score.
But I can't find how to get the top_k path (max-score) with api of k2. (Now just support best_path).
So please add some features or fix them if you think what i say is reasonable

**Comment by Slyne** [comment]
@aif-tuenguyen  Did you figure it out how to do decoding on lstm decoder in k2?
