### ISSUE TITLE
Decode or combine the neural net outputs with a fsa imported from kaldi (HCLG)? 

### ISSUE THREAD

**Issue by felixmcgregor** [k2-fsa/k2#1146]
Is there a way to do the graph computation at decoding time with a graph built with Kaldi which has some context dependency and a different topology like a HCLG.fst in k2? 

The reason for the HCLG is I have trained a Wav2Vec2 model using LF-MMI with Kaldi alignments.

It seems the main stumbling block is that the graph uses transition-ids on the input labels of the FST which kaldi gets from the transition model at decode time, and the output of the nnet being pdf-ids. The other being multiple final states.

So, given a nnet outputting pdf-ids and an HCLG taking transition-ids, would it make sense to 
* perhaps construct a different graph given the transition model
* or does it make sense to do the conversion as an intermediate step (something like `ApplyTransitionModelOnIlabels`)? 

Any other suggestions also welcome

**Comment by csukuangfj** [comment]
Yes,I think it's possible.

You need the following steps:

1. Convert HCLG from openfst to k2. This can be easily done by APIs from k2.Fsa

2.Remove epsilon from HCLG in k2

3. Convert the the input label of HCLG in k2 from transition id to pdf id.

4. That's it. You can use the resulting HCLG in k2 for decoding.

**Comment by felixmcgregor** [comment]
Thanks for the reply, works like a charm!
