### ISSUE TITLE
Support for Pytorch 2.0

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/k2#1159]
Is there any plan to support pytorch 2.0 :

https://pytorch.org/get-started/pytorch-2.0/

The release should be beginning of march

Thank you !

**Comment by csukuangfj** [comment]
Yes, we will support PyTorch 2.0 once it is released. 

I think PyTorch 2.0 is backward compatible, so it should be easy to support it.

**Comment by GeorgeLiou** [comment]
> Yes, we will support PyTorch 2.0 once it is released.
> 
> I think PyTorch 2.0 is backward compatible, so it should be easy to support it.

Hi, csukuangfj, 

[pytorch 2.0 has been released](https://pytorch.org/blog/pytorch-2.0-release/), 
and even [Anaconda supported python3.11 on numpy, scipy, scikit-learn...](https://anaconda.cloud/anaconda-repo-news).

It seems that pytorch 2.0 and python 3.11 has many improvements, 
which new features in pytorch 2.0 can we expected to be introduced to k2?

Thank you :)

**Comment by csukuangfj** [comment]
> Is there any plan to support pytorch 2.0 :
> 
> 
> 
> https://pytorch.org/get-started/pytorch-2.0/
> 
> 
> 
> The release should be beginning of march
> 
> 
> 
> Thank you !

https://k2-fsa.github.io/k2/installation/pre-compiled-cuda-wheels-linux/2.0.0.html

This page contains pre-compiled k2 wheels for torch 2.0.


Basically, you don't need to change any code of k2 to support torch 2.0.

**Comment by ezerhouni** [comment]
@csukuangfj I tried using torch.compile and it crashed. I will double check as it was a quick test

**Comment by csukuangfj** [comment]
> > Yes, we will support PyTorch 2.0 once it is released.
> 
> > 
> 
> > I think PyTorch 2.0 is backward compatible, so it should be easy to support it.
> 
> 
> 
> Hi, csukuangfj, 
> 
> 
> 
> [pytorch 2.0 has been released](https://pytorch.org/blog/pytorch-2.0-release/), 
> 
> and even [Anaconda supported python3.11 on numpy, scipy, scikit-learn...](https://anaconda.cloud/anaconda-repo-news).
> 
> 
> 
> It seems that pytorch 2.0 and python 3.11 has many improvements, 
> 
> which new features in pytorch 2.0 can we expected to be introduced to k2?
> 
> 
> 
> Thank you :)
> 
> 

I am afraid not.

Actually, the core part of k2 doesn't depend on torch. The C++ part uses torch to manage CUDA memory allocation, though we can use other allocators if available.

**Comment by csukuangfj** [comment]
> @csukuangfj I tried using torch.compile and it crashed. I will double check as it was a quick test

Anything related to k2 used in the module that is called with torch.compile() will not work, the same thing goes to torch.jit.trace() and torch.jit.script().
