### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by treya-lin** [k2-fsa/k2#1161]
Not a big finding but just a minor typo in documentation: 

https://k2-fsa.github.io/k2/core_concepts/index.html#example-1-autograd-in-tropical-semiring

```
fsa_vec = k2.create_fsa_vec([fsa])
total_scores = fsa.get_tot_scores(log_semiring=False, use_double_scores=False)
```
should be 
```
fsa_vec = k2.create_fsa_vec([fsa])
total_scores = fsa_vec.get_tot_scores(log_semiring=False, use_double_scores=False)
```
right : )

**Comment by csukuangfj** [comment]
Yes, you are absolutely right.

Would you mind creating a pull-request to fix it?

**Comment by treya-lin** [comment]
> Yes, you are absolutely right.
> 
> Would you mind creating a pull-request to fix it?

Sure. Just created it https://github.com/k2-fsa/k2/pull/1162 . Cheers.
