### ISSUE TITLE
problem build from source

### ISSUE THREAD

**Issue by tomato18463** [k2-fsa/k2#1189]
I am trying to build k2 from source on Ubuntu. My pytorch version is 1.10.2 and CUDA version 11.4.120. Since I can't find a pytorch wheel built with cuda 11.4 [here](https://download.pytorch.org/whl/torch_stable.html), I end up install the pytorch wheel built with cu113. 

Then I get this error when I build k2:

`AssertionError: PyTorch is built with CUDA version: 11.3.
The current running CUDA version is: 11.4.120`

Is there anyway to safely bypass this, or I have to adjust my pytorch build or CUDA version?

Thanks!

**Comment by csukuangfj** [comment]
If you want to bypass it, you can change
https://github.com/k2-fsa/k2/blob/460c841d0329273e4d8ee60e204d450e48a78245/cmake/torch.cmake#L55
to
```
 message(STATUS
```

But we are not sure whether there would be issues during running time. If all tests get passed after building k2, then it is fine.

---

If you want to change your cuda toolkit, please refer to
https://k2-fsa.github.io/k2/installation/cuda-cudnn.html

**Comment by tomato18463** [comment]
> If you want to bypass it, you can change
> 
> https://github.com/k2-fsa/k2/blob/460c841d0329273e4d8ee60e204d450e48a78245/cmake/torch.cmake#L55
> 
> 
> to
> ```
>  message(STATUS
> ```
> 
> But we are not sure whether there would be issues during running time. If all tests get passed after building k2, then it is fine.
> 
> If you want to change your cuda toolkit, please refer to https://k2-fsa.github.io/k2/installation/cuda-cudnn.html

Thanks for your reply. I am now trying to switch to pytorch2.0 + cuda 11.8. I'd like to ask if the pre-compiled wheels [here](https://k2-fsa.github.io/k2/installation/pre-compiled-cuda-wheels-linux/2.0.0.html) are built from stable version versions, or they are built from nightly versions? Thanks again!

**Comment by csukuangfj** [comment]
The wheels are built from a specific commit and you can find the date of the commit from the filename of the wheels.

You can install k2 from the pre-compiled wheels. We will try to keep that page up to date.

---

We suggest that you always use the latest wheel if you install k2 from pre-compiled wheels.

If you want to install k2 from source, then please always use the latest master of k2.

**Comment by tomato18463** [comment]
> The wheels are built from a specific commit and you can find the date of the commit from the filename of the wheels.
> 
> You can install k2 from the pre-compiled wheels. We will try to keep that page up to date.
> 
> We suggest that you always use the latest wheel if you install k2 from pre-compiled wheels.
> 
> If you want to install k2 from source, then please always use the latest master of k2.

I see. Thanks!

**Comment by tomato18463** [comment]
I get it to work by adjusting my cuda and pytorch versions.
