### ISSUE TITLE
When to use k2.ctc_topo with modified=True?

### ISSUE THREAD

**Issue by wangtiance** [k2-fsa/k2#1224]
The result seems to be the same as the "compact CTC" from https://arxiv.org/abs/2110.03098, where the number of arcs is linear with the number of tokens. The paper says that in training, the input needs to be modified. What about inference? Can it be used directly?

**Comment by danpovey** [comment]
I think the main saving is memory.  Not 100% sure though.  Can be used for inference but i think after composing with any language model the difference may be small.

**Comment by wangtiance** [comment]
Thanks Dan. I did some tests, for Librispeech's 3-gram it only reduced the number of arcs of HLG by less than 5%. But for my own G (with only a few keywords) the reduction is significant, like 80%.
