### ISSUE TITLE
Provide manylinux wheels

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#1227]
We are providing pre-compiled k2 wheels that are built on Ubuntu 20.04. The consequence is that users with older linux systems, e.g., Ubuntu 18.04, CentOS 7, etc, cannot use them since the wheels link symbols from high versions of libstdc++.so and libc.so.

The fix is to provide pre-compiled k2 wheels that are able to run on **many** linux systems, especially on older linux systems, e.g., Ubuntu 18.04, CentOS 7, etc.

I just managed to build a manylinux2014 wheel 
`k2-1.24.3.dev20230715+cuda10.2.torch1.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`

It can be downloaded from
https://huggingface.co/csukuangfj/k2/resolve/main/cuda/k2-1.24.3.dev20230715%2Bcuda10.2.torch1.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

Would be nice if someone can test it on CentOS 7 or some similar older systems. If it works well, I will provide wheels
for other combinations of PyTorch and CUDA.

**Comment by desh2608** [comment]
@salah-zaiem perhaps this would work for your cluster?
