### ISSUE TITLE
Possible to install k2 in MacOS Apple Silicon

### ISSUE THREAD

**Issue by nabil6391** [k2-fsa/k2#1240]
Thanks for the k2-icefall package, I usually use colab to run my tests on k2. However thought of installing k2-icefall in my m2 macbook. However looks like there are no pre-compiled cpu for arm in macos. 

Requesting guidance on K2's compatibility and any potential workarounds for Apple Silicon users.

**Comment by csukuangfj** [comment]
@nabil6391 
Please have a look at https://k2-fsa.github.io/k2/cpu.html

We just supported it. Could you have a test?

**Comment by csukuangfj** [comment]
<img width="722" alt="Screenshot 2023-08-23 at 23 07 13" src="https://github.com/k2-fsa/k2/assets/5284924/e3ae0830-cdd0-46a0-a926-2b5a9ac7a345">

**Comment by nabil6391** [comment]
This is the error I get:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/site-packages/k2/__init__.py", line 23, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/site-packages/_k2.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/site-packages/_k2.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/site-packages/_k2.cpython-310-darwin.so' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/kaldi/lib/python3.10/site-packages/_k2.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by csukuangfj** [comment]
Is it an installation error or a runtime error?

**Comment by csukuangfj** [comment]
I think I know the issue now. Please wait for a moment; I am rebuilding a wheel for you.

**Comment by csukuangfj** [comment]
Turns out cibuildwheel does not support installing an arm64 wheel for macos in github actions. Sorry that we cannot provide pre-compiled wheels for macos M1.

Please use
```bash
git clone https://github.com/k2-fsa/k2
cd k2
python3 setup.py install
```
to install k2 from source.

**Comment by nabil6391** [comment]
Was able to install k2 from source. Thanks

**Comment by csukuangfj** [comment]
@nabil6391 

Finally, we provide pre-built wheels for macOS M1 starting from torch 2.3.0

Please see

https://k2-fsa.github.io/k2/cpu.html

![Screenshot 2024-04-25 at 11 16 51](https://github.com/k2-fsa/k2/assets/5284924/68be8e42-6bb5-45fe-bd0b-8bebe3e46839)
