### ISSUE TITLE
in doc of k2 ，there is a  mistake in explain  for autograd in log semiring

### ISSUE THREAD

**Issue by l2009312042** [k2-fsa/k2#1253]
https://k2-fsa.github.io/k2/core_concepts/index.html#
![image](https://github.com/k2-fsa/k2/assets/5296159/61003266-0963-4572-8346-fa564b3c5b91)

the  fsa should be  fsa_vec

**Comment by csukuangfj** [comment]
Yes, you are right. Would you mind creating a PR to fix it?

**Comment by l2009312042** [comment]
yes, the pr is  https://github.com/k2-fsa/k2/pull/1254
