### ISSUE TITLE
Question about the implementation of MWER

### ISSUE THREAD

**Issue by lawlict** [k2-fsa/k2#1260]
Hi, I'm curious that mwer_loss in k2 doesn't substract the average wer, which is emphasized in the paper:
![image](https://github.com/k2-fsa/k2/assets/35951198/084c6f70-10eb-43cf-a183-298324a03689)

And the code is: https://github.com/k2-fsa/k2/blob/master/k2/python/k2/mwer_loss.py#L117
![image](https://github.com/k2-fsa/k2/assets/35951198/13ec7ed1-c975-40e1-8feb-5e551b032618)

So does it really matter to subtract the average wer? (I guess no?)

Look forward to your kind response.

**Comment by danpovey** [comment]
I think you are referring to a paper from Google.  I was confused by that statement in the paper.  There are
two choices: either \hat{W} is with gradient, in which case the gradient of the MWER expression reduces to exactly zero;
or \hat{W} is without gradient, in which case it has no effect on the gradient of the resulting expression.  So either
way it should have no effect.
If you compute the gradients "manually", for example on a lattice, or on a collection of n-best paths (e.g. see my thesis), there is actually a "minus average of word error" expression that appears in the computation; but if
you are using some kind of autograd framework this is implicit and you don't have to do it.

**Comment by lawlict** [comment]
@danpovey I get it. Thanks for your answer and the great work!
