### ISSUE TITLE
Question about k2.union() function.

### ISSUE THREAD

**Issue by lawlict** [k2-fsa/k2#1262]
Hi, I hope to take ```k2.union()``` function to merge the nbest paths into one fsa. The result is correct, but some how not as expected. 
Here is a simple example:
```
import k2
fsa_a = k2.linear_fsa([1,2,3])
fsa_b = fsa_a
fsas = k2.create_fsa_vec([fsa_a, fsa_b])
fsa_union = k2.union(fsas)
fsa_a.draw('fsa_a.png', title='fsa_a')
fsa_b.draw('fsa_b.png', title='fsa_b')
fsa_union.draw('fsa_union.png', title='fsa_union')
```
Since fsa_a and fsa_b are the same, I expect that fsa_union would be equal to fsa_a. But fsa_union actually looks like:
![image](https://github.com/k2-fsa/k2/assets/35951198/c6f582b4-bdea-4595-8834-c43fdadf994b)
Is there any way to simplify fsa_union?

Best wishes.

**Comment by csukuangfj** [comment]
I think fsa union follows the following semantics from openfst.
https://www.openfst.org/twiki/bin/view/FST/UnionDoc

**Comment by lawlict** [comment]
Yes, the result of ```union()``` function is correct, and I wonder is there anyway to simplify it?

**Comment by danpovey** [comment]
You could determinize it with epsilon removal, if supported, or remove epsilons then determinize.   I don't recall how good the support in k2 for determinization is, it is only supported on CPU I think.

**Comment by lawlict** [comment]
@danpovey I see. Thank you for your response.
