### ISSUE TITLE
ModuleNotFoundError: No module named '_k2'

### ISSUE THREAD

**Issue by MisakaMikoto-o** [k2-fsa/k2#1275]
hello, i have installed k2 with 'pip install k2' in linux aarch64, but when i importing it in python, there is a error: `File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/tibetan/lib/python3.9/site-packages/k2/__init__.py", line 23, in <module>
    from _k2 import DeterminizeWeightPushingType
ModuleNotFoundError: No module named '_k2'`

thank you very much if you can tell me how solve it

**Comment by csukuangfj** [comment]
> hello, i have installed k2 with 'pip install k2' in linux aarch64

1. We don't provide pre-built wheels for `aarch64`
2. please follow the doc to install k2 from source

**Comment by MisakaMikoto-o** [comment]
have sovled by installing k2 and kaldifeat from source, thank you!
