### ISSUE TITLE
ModuleNotFoundError: No module named '_k2'

### ISSUE THREAD

**Issue by AKG-0501** [k2-fsa/k2#1278]
I got this error when using k2 after installing it
Traceback (most recent call last):
  File "/home/ljn/anaconda3/envs/eend/lib/python3.7/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ModuleNotFoundError: No module named '_k2'

**Comment by csukuangfj** [comment]
Could you describe how you installed k2?

**Comment by AKG-0501** [comment]
> Could you describe how you installed k2?

I use this command：
pip install k2==1.23.3

**Comment by csukuangfj** [comment]
Please uninstall it

and

follow our doc to install k2

and

retry.

**Comment by AKG-0501** [comment]
> Please uninstall it
> 
> and
> 
> follow our doc to install k2
> 
> and
> 
> retry.

I can't find the installation documentation, can you send me a link.thanks

**Comment by csukuangfj** [comment]
Please see

https://k2-fsa.github.io/k2/installation/from_wheels.html#linux-cuda-example
