### ISSUE TITLE
frame level RNNT-loss

### ISSUE THREAD

**Issue by uni-saurabh-vyas** [k2-fsa/k2#1305]
I am trying to get frame level RNNT-loss, I looked into the source code,and see its calling Mutual Information Recursion 
 https://github.com/k2-fsa/k2/blob/master/k2/python/k2/rnnt_loss.py#L1458

 But even if I pass reduce to None, the scores have dim of [B], I want frame level loss for each cut in a batch 

 I looked at https://github.com/k2-fsa/k2/blob/master/k2/python/k2/mutual_information.py#L24, but it also directly return the final loss for a cut, not frame level. 

 Is there any way of achieving this without modifying c source at https://github.com/k2-fsa/k2/blob/21302dae6cdbaa25c5b851f35329e592f5bf12d5/k2/python/csrc/torch/mutual_information_cuda.cu#L91 ?

**Comment by danpovey** [comment]
The RNN-T loss is a recursion that doesn't very naturally give rise to a per-frame loss.  Normally when we need things that are per-frame we add a CTC loss and do that stuff with CTC.

**Comment by uni-saurabh-vyas** [comment]
I see, Thanks for your prompt response.
