### ISSUE TITLE
Issue encountered while finding shortest path in composed FSA

### ISSUE THREAD

**Issue by ChenxuKwok** [k2-fsa/k2#1315]
**Hi developers,**

I have been working with your library to build and compose my own finite state automata (FSA). The process of composing the FSAs seems to proceed without any errors.

Here is the code I'm using for composing the FSAs:

```python
resultgraph_1 = k2.compose(ctc_fsa, decode_fsa, treat_epsilons_specially=True)
resultgraph = k2.compose(resultgraph_1, sapfsa, treat_epsilons_specially=True)
resultgraph = k2.arc_sort(resultgraph)
result_graph = k2.connect(resultgraph)
result_graph = k2.arc_sort(result_graph)
fsa_vec = k2.create_fsa_vec([result_graph])
```

However, when I attempt to find the shortest path using the following command:

```python
result = k2.shortest_path(fsa_vec, use_double_scores=True)
```

I encounter the following error:

```
[F] /var/www/k2/csrc/fsa_utils.cu:737:k2::GetStateBatches(k2::FsaVec&, bool)::<lambda(int32_t)> Check failed: dest_state > state_idx01 (1 vs. 1)
```

It seems like there is a problem when trying to compute the shortest path after composing the FSAs. Could you please assist in identifying what might be causing this issue?

Thank you for your help!

Best regards,  
Chenxu

**Comment by csukuangfj** [comment]
Is the FSA empty or is there a cycle?

please check it.

**Comment by ChenxuKwok** [comment]
really make sence, thank you
