### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#167]
-- Found PythonInterp: /home/linuxbrew/.linuxbrew/bin/python3.8 (found version "3.8.5")
-- Found PythonLibs: /home/linuxbrew/.linuxbrew/opt/python@3.8/lib/libpython3.8.so
-- pybind11 v2.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
CMake Error at cmake/torch.cmake:10 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:100 (include)

-- Configuring incomplete, errors occurred!
See also "/home/storage06/dpovey/k2/build/CMakeFiles/CMakeOutput.log".
See also "/home/storage06/dpovey/k2/build/CMakeFiles/CMakeError.log".

**Comment by danpovey** [comment]
maybe I just need to install torch...

**Comment by csukuangfj** [comment]
Yes, you are right. All you need is `pip install torch`.

You can disable PyTorch by using
```sh
cd build
cmake -DUSE_PYTORCH=OFF ..
```

**Comment by danpovey** [comment]
Yeah.  I have been spending the last hour or so trying to install torch.
It keeps timing out.
I am trying to get the whl file from a VM I have in Hong Kong, so I can scp
it back over here.

**Comment by csukuangfj** [comment]
Tsinghua provides a mirror that can be accessed faster inside China.

https://pypi.tuna.tsinghua.edu.cn/simple/torch/ contains `*.whl` for various versions of PyTorch.

I guess [torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl][1] is what you want.

[1]: https://pypi.tuna.tsinghua.edu.cn/packages/8c/5d/faf0d8ac260c7f1eda7d063001c137da5223be1c137658384d2d45dcd0d5/torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl#sha256=5357873e243bcfa804c32dc341f564e9a4c12addfc9baae4ee857fcc09a0a216

**Comment by qindazhu** [comment]
+1 for Tsinghua mirror. @danpovey you can add Tsinghua mirror as the default channel for pip, it will be much faster than the default.
```
pip install pip -U
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by danpovey** [comment]
Yeah that is the source I am using but it is too slow.
Could be our network is the problem.

**Comment by danpovey** [comment]
... I managed to install it after obtaining the pip file from a VM in Hong
Kong that I maintain.

**Comment by qindazhu** [comment]
Then it must be the issue of Xiaomi network... I could get Torch in 3 minutes at home..

> Yeah that is the source I am using but it is too slow. Could be our network is the problem.
> […](#)
