### ISSUE TITLE
Returning things as PyTorch tensors

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#169]
Guys,
This is an issue for the python interface...
there will be lots of times when someone wants to access a member of, say, a class, that is of type Array1.
In these instances we will want to make the Array1 appear as a PyTorch tensor. 
I mean, I suppose we could do this when we wrap Array1 itself.
I believe this should be possible, assuming we were using a pytorch context (and maybe even if not).
The same issue arises with Array2 and Tensor, but less often.

**Comment by csukuangfj** [comment]
I am planning to wrap `Array1`, `Array2` and `Tensor` to `torch::Tensor`.
Since k2 depends on `libtorch`, we are not limited to DLPack and we can use whatever functions PyTorch provide.

Should we organize the python wrapper as something like the following?

```
- k2
  - python
    - csrc
       - torch
       - tensorflow
       - ....
```
where the folder `torch` contains everything related to `PyTorch`. We can choose whether PyTorch or tensorflow is
going to be added into the k2 pip package.

**Comment by qindazhu** [comment]
We did the same things to host `Array1` in Python binding code before, not sure if it contains all your needs
https://github.com/k2-fsa/k2/blob/master/k2/python/csrc/array.cc

**Comment by danpovey** [comment]
Ah thanks,
I am open to reorganizing the interfaces and having PyTorch and CUDA
versions.  In fact, to handle the context objects properly we may need
to do that (?).
I'm not sure what the implications are of using native torch stuff, vs.
dlpack, but at this stage I think it's good to explore different options and
alternatives- unless anyone has an objection.

**Comment by danpovey** [comment]
.. i mean PyTorch and TF.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/k2/blob/master/k2/python/csrc/array.cc is not powerful enough. We can return a `torch::Tensor` instead of a `DLPackArray`.

**Comment by qindazhu** [comment]
> we are not limited to DLPack and we can use whatever functions PyTorch provide

I just thought using DLPack will make it easy to maintain those bindings in the future

**Comment by qindazhu** [comment]
> https://github.com/k2-fsa/k2/blob/master/k2/python/csrc/array.cc is not powerful enough. We can return a `torch::Tensor` instead of a `DLPackArray`.

Yes, Agree with you.. just paste to link to show we can do what @danpovey wants.

**Comment by csukuangfj** [comment]
I can write a demo to show

- how to pass a `k2::Array1` to python as a `torch::Tensor`
- how to construct a `k2::Array1` via a `torch::Tensor` passed from Python

with memory sharing between `k2::Array1` and `torch::Tensor`.

**Comment by danpovey** [comment]
I'm open minded on this, right now.   It would be nice to at least familiarize ourselves with the options before committing to one (if we do end up having to make a hard decision).
