### ISSUE TITLE
Sort with operator

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#176]
Guys,
I spoke with some guys at NVidia to get advice on how we'd implement an interface like
```
template <typename T, typename Op>
void SortSublists(Ragged<T> &src, Array1<int32_t> *order);
```
They advised this
  https://moderngpu.github.io/segsort.html

It will require adding it as another dependency (moderngpu) but I think it's header only.  Apparently it is likely to be added to thrust at some point (i.e. that sort thing).  Sorry i dont have much energy right now so rather than doing it myself I am putting the info here. 
Eventually we'll want to make it customizable with sorting function-object, actually we should make it
template <typename T, typename Op=LessThan<T> >
struct LessThan<T> { 
  inline __host__ __device__ __forceinline__ operator (const T &a, const T &b) const { return (a  < b); }
};
(+device copy constructor as needed)

**Comment by qindazhu** [comment]
OK, I can do this (maybe after getting all existed `array_ops` algorithms tested) if there's no other guy take the task. 

Not go to the detailes of moderngpu for now, just to make sure,  couldn't we just use radix sort from cub? https://nvlabs.github.io/cub/structcub_1_1_device_segmented_radix_sort.html

**Comment by danpovey** [comment]
Radix sort doesn't support segmented sort (i.e. sort within segments).  You
could of course create one big key, but it operates 4 bits at a time,
so suppose you have a 64-bit key, that would be 16 passes over the data.

**Comment by qindazhu** [comment]
OK, as we discussed offline, will use https://nvlabs.github.io/cub/structcub_1_1_device_segmented_radix_sort.html for integer type and moderngpu for other types for efficiency (i.e. without bit-wise  transformations)

**Comment by csukuangfj** [comment]
I'd like to wrap `segsort` from moderngpu to k2.

**Comment by qindazhu** [comment]
> I'd like to wrap `segsort` from moderngpu to k2.

Thanks!

**Comment by csukuangfj** [comment]
@danpovey 
For this interface

```cpp
template <typename T, typename Op>
void SortSublists(Ragged<T> &src, Array1<int32_t> *order);
```

Is it a in-place sort and does `order` contains the sorted indices?

**Comment by qindazhu** [comment]
> Is it a in-place sort and does order contains the sorted indices?

Yes.

**Comment by danpovey** [comment]
I was thinking it would just output the indices, if we need to sort the
values as well to make that possible then make that arg a pointer pls.

**Comment by danpovey** [comment]
.. and in that case we could make the indices optional.

**Comment by csukuangfj** [comment]
It turns out moderngpu does an in-place sort.  I'll change the interface to

```cpp

template <typename T, typename Op = LessThan<T>>
void SortSublists(Ragged<T> *src, Array1<int32_t> *order);
```

**Comment by danpovey** [comment]
Cool.
