### ISSUE TITLE
Conversion to/from strings

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#178]
Guys,
I dont know where we are with the I/O format right now, but I propose that we find a way to enable I/O to and
from FSAs and strings.
We could have the following options, with defaults:

   acceptor=True   # if true, format is: src_state dest_state label cost.  if false it's src_state dest_state label aux_label cost; the aux_label would be stored as a separate vector of int32.
  negate_scores=False   # if true, the string form has the weights as costs, not scores, so we negate as we read/write

The final-state is of course treated differently.  The format will be like OpenFST, as just:
final_state
(with no cost, since we don't support a cost on the final state, there should be an arc with -1 going to final state, which
has the costs on).

Eventually we'd have options related to symbol tables, i.e. allow the user to supply a symbol table.
 
This interface should probably exist at the C++ level in some form, since the aim is to basically have the same functionality
available from C++ as from Python.

**Comment by qindazhu** [comment]
Actually @csukuangfj wrote a basic version before, so I guess he may be interested in this task.

https://github.com/k2-fsa/k2/blob/960abbcfa75655a858ae2c6e1f5daea0bb7b5470/k2/csrc/host/fsa_util.h#L238-L252

**Comment by csukuangfj** [comment]
I would like to implement it.

**Comment by danpovey** [comment]
Fantastic!

**Comment by csukuangfj** [comment]
Can we assume that the `final_state` has the largest state number?

**Comment by danpovey** [comment]
Yes, it would be an error if not.

**Comment by qindazhu** [comment]
Closed as we have finished this.
