### ISSUE TITLE
Wrapping more of the host code

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#179]
What I did with Connect() was intended as a kind of template for how other algorithms can be wrapped.
I suggest a next one that could be wrapped is Intersect(), if someone has time (no hurry!)

**Comment by qindazhu** [comment]
I was planning to do this after testing current Fsa struct as those wrappings are not so hurry and would be straightforward (and it can resue those tests I written before for host code), but would be happy if other guys (@songmeixu ?) could take the task.

**Comment by qindazhu** [comment]
Closed as we have finished this.
