### ISSUE TITLE
Goal: composition to create supervision FSAs

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#180]
Guys,

Here's something that it would be great to be able to finish within a couple of weeks.  I'd like to be able to do the
following:

  - Create a lexicon.fst in Kaldi and write it as a text file.
  - Convert that to a k2 FSA (with the olabels as a separate vector)
  - Do Invert() to swap the olabels and ilabels, as we need to compose on the word labels
  - Convert a string (a supervision) to a linear FSA, e.g. could just make the FSA as a string.
  - Compose the lexicon FSA and the linear supervision FSA
  - Use the arc mapping to replace the word labels on the linear supervision FSA with the phone labels

This will require writing quite a bit of code, but I think it's mostly straightforward.  I have not had enough energy to be extremely pro-active with some of this stuff.  If there's anything you guys need clarification on, let me know.

**Comment by chenguoguo** [comment]
I started taking a closer look of the codebase and this might be something that I can help with if it's not assigned yet.

**Comment by danpovey** [comment]
Fantastic!!
Bear in mind, though, this this is a medium-term goal as there are many
pieces that need to be finished before this is done.
For example:
   - Add Python wrapping for the code in csrc/ (currently we only have it
for csrc/host/)
   - Add and test interface to construct k2::Fsa from string and output to
string
Will add more detail in a bit...

**Comment by danpovey** [comment]
A sub-task that you could start with, Guoguo, is to begin by adding support
for weights in FsaToString and StringToFsa in the host/
subdirectory.  A couple weeks ago I added the weights to the Arc in the
host/ dir (they had previously been separate).

I commented on an issue recently about what the options for the conversion
to/from strings would look like:

https://github.com/k2-fsa/k2/issues/178

Fangjun said he would look at that issue (178) more broadly, but you could
start with that small part of it to familiarize yourself with the workflow,
I don't think that will inconvenience him.

**Comment by csukuangfj** [comment]
Glad to see a new contributor.

**Comment by chenguoguo** [comment]
Sounds good to me. I'll spend some time next week to look into adding weights to FsaToString. I'll get back to you/Fangjun if I need some clarification.

**Comment by csukuangfj** [comment]
@danpovey 
Do you want this to be implemented in Python or in C++?

**Comment by danpovey** [comment]
Each bullet point would be invoked separately from Python, although of course  the appropriate wrappers would call C++ code.

**Comment by qindazhu** [comment]
Closed as we have fininshed this.
