### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#188]
Guys (and especially @csukuangfj) just to let  you know that we are working under a certain amount of time pressure.  We have Nov 1st as a hard deadline to release *something*, which should at least include an example with CTC and maybe one with LF-MMI.  Ideally the key parts of k2 itself will be mostly finished by mid-October or so, which will give us time to test and tune recipes and integration with Lhotse. 

Any progress on the `issues` will be appreciated.

**Comment by csukuangfj** [comment]
thanks for the remainder.

**Comment by pzelasko** [comment]
Is there anything additional that you need on Lhotse's side?

**Comment by danpovey** [comment]
Was going to ask Junbo (I think we did ask him) to implement data-prep for
the 100-hour subset Librispeech.
(Or all the parts of the data, actually, but we'd use the 100 hour part for
example scripts.)
We started thinking of WSJ but we don't have that data here, apart from
WSJ0.
It's a shame there aren't more medium-sized free datasets that are widely
used.

Is there anything additional that you need on Lhotse's side?

**Comment by pzelasko** [comment]
Yeah I agree with that sentiment.

What about reading/applying lexicons and alignment supervisions? Unless you want to train a graphemic model in fully E2E manner.
