### ISSUE TITLE
Will Lothse dealing with long recordings carry over to decoding?

### ISSUE THREAD

**Issue by thschaaf** [k2-fsa/k2#198]
At the Kaldi Community Roadmap Sanjeev suggested adding this as an issue that is not forgotten.
''Answered orally: we need to think through this.  Make this an “issue” on GitHub so we don’t forget?''

Question was came from the context of Lhotse: 
Does the ability to deal with long recordings for training carry over to decoding and (force) alignments?
In particular recordings that are >=1h.

Best,
-Thomas

**Comment by qindazhu** [comment]
I guess so, but I think it's better if you create the issue in https://github.com/pzelasko/lhotse and @pzelasko may answer you .

**Comment by pzelasko** [comment]
Hmm, I believe the question has two sides:

1) do we support long recording in the training: yes, Lhotse can load them for you and prepare suitable supervision tensors. How long can these recordings exactly be actually depends on the model architecture and your GPU's memory size (and batch size).

2) do we support long recordings in the decoding: offline -> yes, the same situation as 1); online -> this will require a streaming inference runtime compatible with K2, which is likely future work.

**Comment by qindazhu** [comment]
]
