### ISSUE TITLE
add openfst support for fst read

### ISSUE THREAD

**Issue by chenguoguo** [k2-fsa/k2#200]
- [x] replace the `negate_scores` option with `openfst`
- [x] support final states with weight when `openfst` is true
- [x] support multiple final states when `openfst` is true

**Comment by danpovey** [comment]
Yes.  Bear in mind the equivalence between the two formats.  We represent final-probs as "special arcs" because it greatly simplifies algorithms.

**Comment by chenguoguo** [comment]
Close this via https://github.com/k2-fsa/k2/pull/202
