### ISSUE TITLE
TODO: check Cuda error for every kernel launch in debug mode

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#210]
FYI, Added as a TODO, just to make debug easy by checking error immediately after the kernel call.

**Comment by csukuangfj** [comment]
I have encountered this problem while wrapping moderngpu.

**Comment by qindazhu** [comment]
yeah, it's hard to debug such bugs...

**Comment by csukuangfj** [comment]
We also need a stack backtrace when a check fails.

**Comment by danpovey** [comment]
It is supposed to do that:
    K2_DCHECK_CUDA_ERROR(err);

**Comment by qindazhu** [comment]
`K2_DCHECH_CUDA_ERROR` does not call `cudaGetLastError` now, seems we need a version which calls `cudaGetLastError` in debug and do nothing in release. 

https://github.com/k2-fsa/k2/blob/68a5d00f8af59f56f4ce24776a48d32b616edef1/k2/csrc/log.h#L193-L202

**Comment by danpovey** [comment]
Could be a bug in Eval().  Given the macros as it is, we could maybe just
put cudaGetLastError() as the arg to that macro invocation.
Or perhaps check twice: first the kernel return code and then the
cudaGetLastError()?
Might not need new macro.

**Comment by qindazhu** [comment]
Ok, will call `K2_DCHECK_CUDA_ERROR(cudaGetLastError());` (seems calling once is good enough for us as if the kernel returns an error, we will also get the error by calling `cudaGetLastError()`, we can update this if we need to handle complex asynchronous launch error. )

**Comment by qindazhu** [comment]
Fixed in https://github.com/k2-fsa/k2/pull/215, Will close this issue.
