### ISSUE TITLE
Is graphviz now a required dependency for k2 python package?

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#211]
I notice we import `graphviz` in `python/k2/fsa.py` which means `k2` python package requires `graphviz` as a dependency now. Is that necessary? Can we just put those `print to dot` code in a separate file and import `graphviz` there? Then user could import k2 without `graphviz` and just install `graphviz` when they really want to print FSA (I guess most of users will not do this?)

```
24:   File "/home/storage23/qiuhaowen/k2/k2/python/tests/arc_test.py", line 13, in <module>
24:     import k2
24:   File "/home/storage23/qiuhaowen/k2/k2/python/k2/__init__.py", line 2, in <module>
24:     from .fsa import Fsa
24:   File "/home/storage23/qiuhaowen/k2/k2/python/k2/fsa.py", line 16, in <module>
24:     from graphviz import Digraph
24: ModuleNotFoundError: No module named 'graphviz'
1/1 Test #24: arc_test_py ......................***Failed    4.64 sec
```

**Comment by csukuangfj** [comment]
Yes, you are right. `Fsa` has a `to_dot` method, which requires `pip install graphviz`.
