### ISSUE TITLE
Clone() for Array1 and Array2

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#217]
Can we please have Clone() functions for Array1 and Array2, that will give a new array on the same device?

BTW there is something I'm not very satisfied about the current design, that some functions are members but others are not, even though they might most naturally be members.  I'm thinking for now we could put them as non-member functions like ToContiguous(), in array_ops.h.

Also my intention was that any functions involving Ragged would go in ragged_ops.h, not array_ops.h.  Just FYI: not urgent or important.

**Comment by qindazhu** [comment]
> Ragged would go in ragged_ops.h, not array_ops.

 Will do this after tested all methods in ragged.h. Actually there are a lot of ops functions now in `ragged.h` instead of `ragged_ops.h`

**Comment by danpovey** [comment]
BTW, this is done for array1 but not array2.
