### ISSUE TITLE
Bugs in GetFsaBasicProperties

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#219]
For the following fsa
https://github.com/k2-fsa/k2/blob/d291daf7a88d50907d2b1039ca6033f307995a65/k2/csrc/fsa_algo_test.cu#L26-L38

It prints
```
"Valid|Nonempty|TopSorted|TopSortedAndAcyclic|ArcSortedAndDeterministic|EpsilonFree|MaybeAccessible|Serializable"
```

----

**ArcSortedAndDeterministic** should NOT be there.

**Comment by danpovey** [comment]
OK, that seems to be a case of missing code.  Will fix it...

**Comment by danpovey** [comment]
Can you please see if this proposed fix works and commit if so?  In fsa.cu, I propose to add the `else` branch to the following if-statement.  Around line 170.
```
    if (idx2 == 0) {
      // First arc leaving this state records that this state has arcs leaving                                                                                                  
      // it.                                                                                                                                                                    
      if (arc.dest_state != arc.src_state)
        reachable_data[num_states + idx01] = 1;
    } else {
      int32_t symbol_diff = arc.symbol - prev_arc.symbol;
      if (symbol_diff <= 0) neg_properties |= kFsaPropertiesArcSortedAndDeterministic;
      if (symbol_diff < 0) neg_properties |= kFsaPropertiesArcSorted;
    }
```

**Comment by danpovey** [comment]
Incidentally, I am thinking of making a change so that in terms of arc-sorting, the symbols are viewed as uint32_t.  That would ensure that epsilon arcs would always be at the beginning, which would be simpler for composition algorithms.  I haven't made up my mind yet though.  It would of course require some code changes, here and elsewhere.

**Comment by csukuangfj** [comment]
> Can you please see if this proposed fix works and commit if so? In fsa.cu, I propose to add the else branch to the following if-statement. Around line 170.

@danpovey 

Do we need to check that `prev_arc` and `arc` have the same `src_state`? It does not make sense
to compare arc symbols of different nodes.

**Comment by danpovey** [comment]
The fact that idx2 != 0 should guarantee that.

**Comment by csukuangfj** [comment]
> Incidentally, I am thinking of making a change so that in terms of arc-sorting, the symbols are viewed as uint32_t. That would ensure that epsilon arcs would always be at the beginning, which would be simpler for composition algorithms

Is the following the only change needed to push epsilon arcs to the beginning?

From
https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/fsa_algo.cu#L67-L72

to

```cpp

struct ArcComparer {
  __host__ __device__ __forceinline__ bool operator()(const Arc &lhs,
                                                      const Arc &rhs) const {
    return static_cast<uint32_t>(lhs.symbol) < static_cast<uint32_t>(rhs.symbol);
  }
};
```

**Comment by danpovey** [comment]
Yes, but the same change would have to be made in the documentation of
properties and in checking the properties.
It might make more sense, in that case, to just make that field uint32_t.

**Comment by csukuangfj** [comment]
> The fact that idx2 != 0 should guarantee that.

But the problem is that `prev_arc` has a value when `idx012 > 0` instead of `idx2 > 0`:
https://github.com/k2-fsa/k2/blob/cc752e5a8f3ccca80c2f3d6bc546a92a5ae92243/k2/csrc/fsa.cu#L126-L127

I think this is incorrect.

**Comment by danpovey** [comment]
If idx2 > 0 that implies that idx012 > 0.

**Comment by csukuangfj** [comment]
if idx2 > 0, it can guarantee that prev_arc and arc share the same src_state.
However, if idx012 > 0, `prev_arc` and `arc` can have different source states.

**Comment by csukuangfj** [comment]
I would propose
```cpp
if (idx2 > 0) prev_arc = arcs_data[idx012 - 1]; 
```
instead of 
```cpp
if (idx012 > 0) prev_arc = arcs_data[idx012 - 1]; 
```

**Comment by csukuangfj** [comment]
> The fact that idx2 != 0 should guarantee that.

yes, you're right.
