### ISSUE TITLE
k2.Array1, k2.Array2

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#230]
Guys,
This issue is for discussion of the wrapping of `k2.Array1<X>` and `k2.Array2<X>`.   I know we already have some code.
Specifically what I wonder is, what w'll be doing about `k2.Array1<Arc>`, as this is part of FSAs.  Is there any way to make this so it appears to be a PyTorch array of int32_t, of N by 4?  I don't even know if that's the best way.  If it's possible to make PyTorch treat it as an opaque type of 16 bytes, that's fine with me too.
Dan

**Comment by csukuangfj** [comment]
> Specifically what I wonder is, what w'll be doing about k2.Array1<Arc>, as this is part of FSAs. Is there any way to make this so it appears to be a PyTorch array of int32_t, of N by 4?

I think this has already been done.

https://github.com/k2-fsa/k2/blob/b7a900ca6d9bb3ed8a058cd15bb9e9e1bcfd53fa/k2/python/csrc/torch/torch_util.cu#L40-L41

https://github.com/k2-fsa/k2/blob/b7a900ca6d9bb3ed8a058cd15bb9e9e1bcfd53fa/k2/python/csrc/torch/torch_util.cu#L56-L57

There are also python tests for `k2.Array1<Arc>`:

https://github.com/k2-fsa/k2/blob/b7a900ca6d9bb3ed8a058cd15bb9e9e1bcfd53fa/k2/python/tests/array_test.py#L119

https://github.com/k2-fsa/k2/blob/b7a900ca6d9bb3ed8a058cd15bb9e9e1bcfd53fa/k2/python/tests/array_test.py#L143

**Comment by csukuangfj** [comment]
>  If it's possible to make PyTorch treat it as an opaque type of 16 bytes, that's fine with me too.

This is also feasible. We can convert `Array1<Arc>` to a 1-D `complex<double>` torch.tensor
since `complex<double>` occupies 16-byte. There is no **opaque** type in PyTorch.

I think representing `Array1<Arc>` as an Nx4 torch.int32 Tensor is more natural.

**Comment by danpovey** [comment]
Ah I see, so when you do .tensor() on an Array1<Arc> from python you
already get an (N,4) int32 Tensor.  That's fine.

**Comment by csukuangfj** [comment]
I would propose to remove `array.py` in Python. I don't think we need `k2.Array1` and `k2.Array2` in Python.
Whenever a function/methond returns or accepts `k2.Array1`, `k2.Array2`, we can convert it to/from a `torch::Tensor`.

**Comment by danpovey** [comment]
I agree, regarding exposing ArrayN, that it would be better to expose them
as tensors.
