### ISSUE TITLE
Implement transpose function for ragged tensor

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#234]
see GetTransposeReordering(), it's here 
https://github.com/k2-fsa/k2/pull/233
(already merged, but only declared)

**Comment by danpovey** [comment]
[I just want to mention: I realized that the algorithm I used for top-sorting is not correct, so please don't try to debug that right now.  I need to rewrite it and use this function GetTransposeReordering() in it.]

**Comment by csukuangfj** [comment]
I am going to implement the CPU version first and then will convert it to GPU.
