### ISSUE TITLE
LogSumPerSublist

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#254]
We need something like MaxPerSublist that uses the LogAdd operator.  Should work for float and double.  
i.e. the log-add operator implements log(exp(a) + exp(b)), but avoiding exponentiation (and must work for
infinities appropriately).  You can see Kaldi's LogAdd function, there are subtleties involves so it's probably 
better to copy and modify the code.

**Comment by csukuangfj** [comment]
I think K2 already has `LogAdd`:

https://github.com/k2-fsa/k2/blob/d5a296039e891baa50c1a474ab433016931afb65/k2/csrc/host/util.h#L53-L54

https://github.com/k2-fsa/k2/blob/d5a296039e891baa50c1a474ab433016931afb65/k2/csrc/host/util.h#L74-L75

**Comment by danpovey** [comment]
Oh, great.
We may need to make some small modifications to get those to compile on CUDA, apart from adding __host__ __device__.
e.g. not sure if std::numeric_limits is problematic (think it is on some compiler versions).
Looks like things like log1pf exist in CUDA as well:
 https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE

**Comment by qindazhu** [comment]
>  std::numeric_limits is problematic (think it is on some compiler versions)

It's not a compiler version issue, we can't use it in kenerl. Instead, we can use these limits constant value. https://en.cppreference.com/w/cpp/types/climits

**Comment by qindazhu** [comment]
@danpovey I think the original implemetantion in /host has addressed infinity well, am I right? seems we can do nothing besides add `host device forinline`
https://github.com/k2-fsa/k2/blob/d5a296039e891baa50c1a474ab433016931afb65/k2/csrc/host/util.h#L50-L72

BTW, should we use flag `use-fast-math`, https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#intrinsic-functions

**Comment by csukuangfj** [comment]
`-use_fast_math` has been introduced by `moderngpu`:

https://github.com/k2-fsa/k2/blob/d5a296039e891baa50c1a474ab433016931afb65/cmake/moderngpu.cmake#L28

You can verfify that every `.cu` file in k2 is currently compiled with `-use_fast_math` enabled by using

```bash
make VERBOSE=1 context
```

**Comment by qindazhu** [comment]
mm.OK

**Comment by danpovey** [comment]
The current implementation should be OK.
Bear in mind that fast-math is quite dangerous if infinities appear
anywhere in the program, as it makes the assumption that
inf's and nan's will never appear so even if you  explicitly test for that,
the compiler just assumes the test evaluates to false.
We can wait until it becomes an issue in practice though.

**Comment by qindazhu** [comment]
Added in PR https://github.com/k2-fsa/k2/pull/256/files. We may need to test `use_fast_math` stuff later.
