### ISSUE TITLE
GetTransposeReordering efficiency improvements

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#255]
This function will probably become a speed bottleneck at some point.
 
There is a fairly easy speed improvement we can do by using a segmented version of moderngpu's mergesort;
this is relevant in cases where there are 3 axes (e.g. when the Ragged<int32> comes from the
DestStates() function, for an FsaVec).

Something less easy to implement that we can consider later on, is to use facilities from cusparse.  Something
that makes it more complex is that we need to support there being >1 arc from state a to state b, which corresponds
to a duplicate element in a sparse matrix, and it's possible that CuSparse does not support that (although
who knows, it might, for this particular function).

**Comment by csukuangfj** [comment]
> this is relevant in cases where there are 3 axes (e.g. when the Ragged comes from the
DestStates() function, for an FsaVec).

I will update the implementation to handle 3 axes with segmented sort from moderngpu.

RE cusparse, I am going to verify whether cusparse can handle duplicate element after finishing the moderngpu part.

**Comment by danpovey** [comment]
Great!

**Comment by csukuangfj** [comment]
> which corresponds
to a duplicate element in a sparse matrix, and it's possible that CuSparse does not support that (although
who knows, it might, for this particular function).

According to the documentation of cuSparse: https://docs.nvidia.com/cuda/cusparse/index.html#csr-format

> Sparse matrices in CSR format are assumed to be stored in row-major CSR format, in other words, the index arrays are first sorted by row indices and then within the same row by column indices. It is assumed that each pair of row and column indices **appears only once**.

I am writing some code to verify whether it supports duplicate entries.

**Comment by csukuangfj** [comment]
It seems cuSparse works in our case with duplicate elements.
Please see the test code in #429 . I will do some profiling with NVTX_RANGE and compare it with our current implementation

**Comment by danpovey** [comment]
Fantastic!!!
Of course we will need to be on the lookout in case there are changes in
the implementation, so we probably should keep the old code around
as a backup.

**Comment by csukuangfj** [comment]
Closing as moderngpu is faster in this case.  See https://github.com/k2-fsa/k2/pull/429
