### ISSUE TITLE
Implement `compose`

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#281]
I'd like to add a linear-chain CRF example for k2, like the one in GTN <https://github.com/facebookresearch/gtn/blob/master/examples/notebooks/linear_crf.ipynb>

But we don't have `compose` yet. I would like to add `csrc/host/compose.cc` borrowing code from `csrc/host/intersect.cc`.

**Comment by danpovey** [comment]
We don't need special code for composition.  It can be done with
composition, plus the arc_map info it outputs, which can be used to
map the aux_labels.

**Comment by danpovey** [comment]
I mean it can be done with intersection.

**Comment by csukuangfj** [comment]
To `compose(a_fsa, b_fsa)`, we can do
- `a_fsa_projected = project_output(a_fsa, a_aux_labels)`, now `a_fsa_projected` is an acceptor
- `out, arc_map_a, arc_map_b = intersect(a_fsa_projected, b_fsa)`
- use `arc_map_a`, `arc_map_b`, `input labels` of `a_fsa` to set the `input labels` and `aux_labels` of `out`

Is the above process for computing `compose` via `intersect` correct ?

**Comment by qindazhu** [comment]
Yeah. Actually in k2 you can view aux_labels as either ilabels or olabels (the one which is not participating in the operation you are doing is olable. )

RE `project`, which is called `Invert` in k2, you can check the code in https://github.com/k2-fsa/k2/blob/master/k2/csrc/host/aux_labels.h for `Invert` and `AuxMapper`

**Comment by danpovey** [comment]
I don't think you need that many steps.  It's easier to not talk about
composition at all, but just talk about intersection, where the aux_labels
are naturally propagated (in fact, they are treated like any other quantity
that is indexed by arc).

So you just intersect A and B, and when the intersection happens, all
per-arc quantities in A and B are copied to the output via the arc_map.
There is no concept of input labels and output labels, just labels.
Suppose B is L.fst, we can have the labels on the arcs be the words, and
the aux_labels be the phones.  (If aux_labels were a ragged tensor we could
have multiple phones per arc, but for now just assume it's a 1-d tensor
with integers on it).  All the quantities in A and B are copied.  If the
same labels exists in both A and B, if it's a float we add; if it's an
integer, for now we just die if both have it.  In our specific case, if B
is L.fst, the aux_labels are the phones, and they are just copied to the
composed result (A.B).  We can then do Invert() to swap the aux_labels and
the regular labels on the composed result.
