### ISSUE TITLE
K2 installed via pip: cannot import _k2

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#288]
Just letting you know, I tried to install K2 via pip and got the following error on two distinct OS's: MacOS 10.15.7 and Debian 4.9.189

The error message was the same:

```
In [1]: import k2
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a7d26a925823> in <module>
----> 1 import k2

~/miniconda3/envs/lhotse/lib/python3.7/site-packages/k2/__init__.py in <module>
----> 1 from .dense_fsa import dense_fsa
      2 from .fsa import Fsa
      3 from .fsa_algo import arc_sort
      4 from .fsa_algo import connect
      5 from .fsa_algo import intersect

~/miniconda3/envs/lhotse/lib/python3.7/site-packages/k2/dense_fsa.py in <module>
      1 # Copyright (c)  2020  Mobvoi Inc.        (authors: Fangjun Kuang)
      2
----> 3 import _k2
      4 import numpy as np
      5 import torch

ModuleNotFoundError: No module named '_k2'
```

Could that mean that the native library is not packaged along with the python wrapper, or is compiled in a way not compatible with these systems and cannot be imported?

**Comment by csukuangfj** [comment]
Could you please show your `pip install` command? Which version are you installing?

**Comment by pzelasko** [comment]
There you go:

```
→ pip install k2
Collecting k2
  Downloading k2-0.0.6.dev20201028-py36-none-any.whl (6.1 MB)
     |████████████████████████████████| 6.1 MB 4.3 MB/s
Collecting graphviz
  Downloading graphviz-0.14.2-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: torch in /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages (from k2) (1.5.1)
Requirement already satisfied: future in /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages (from torch->k2) (0.18.2)
Requirement already satisfied: numpy in /home/pzelasko/miniconda3/envs/lhotse/lib/python3.7/site-packages (from torch->k2) (1.18.5)
Installing collected packages: graphviz, k2
Successfully installed graphviz-0.14.2 k2-0.0.6.dev20201028
```

**Comment by csukuangfj** [comment]
Does the problem still exist?

```sh
pip install k2==0.0.6.dev20201028
```

Then

```sh
import torch
import k2
```
shoud work.

Note that we have to `import torch` first.

**Comment by csukuangfj** [comment]
I just uploaded a pip package for Python3.7.

**Comment by csukuangfj** [comment]
I don't think it will work on macOS. Currently, only Linux is supported. I am using Ubuntu.

**Comment by pzelasko** [comment]
It helped, I got past this stage now. After that I got CUDA error (itrequired 10.0 so I downgraded), and after fixing it (`conda install -c pytorch cudatoolkit=10.0`, which also downgraded pytorch from 1.6 to 1.4) I have:

```ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory```

**Comment by csukuangfj** [comment]
I don't have much experience with `conda`. Could you use `pip install torch`?
I've tested the pip package with Google Colab, which has Python3.6 and CUDA 10.1

**Comment by csukuangfj** [comment]
As for the PyTorch version, PyTorch 1.6 should work.

**Comment by pzelasko** [comment]
I forced pip to install torch over conda's torch, but it did not help. Then I tried to get the same setup as you, but as soon as I changed CUDA to 10.1, the CUDA error returned:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pzelasko/miniconda3/envs/k2/lib/python3.7/site-packages/k2/__init__.py", line 1, in <module>
    from .dense_fsa import dense_fsa
  File "/home/pzelasko/miniconda3/envs/k2/lib/python3.7/site-packages/k2/dense_fsa.py", line 3, in <module>
    import _k2
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```

In general I am unable to work outside of conda as I currently don't have access to any GPU machine where I would have administrative privileges allowing me to install packages like CUDA/python in the version I want. I guess it leaves me with the option of building from source (I wonder if that works with the old GCC 6.3).

**Comment by csukuangfj** [comment]
Will compile a version for CUDA 10.1. Please wait just for a few minutes.

**Comment by csukuangfj** [comment]
Python 3.6 and Python 3.8 requires 10.1 but Python 3.7 requires 10.0.

**Comment by csukuangfj** [comment]
@pzelasko 
Could you try `pip install k2==0.0.7.dev20201028`? It uses CUDA 10.1

**Comment by csukuangfj** [comment]
Great!


The pip package is built based on the pullrequest #282. Some of the Python APIs have been changed. The Colab notebook listed in Readme.md might be helpful.

Thursday, 29 October 2020, 00:29 +0800 from notifications@github.com  <notifications@github.com>:
