### ISSUE TITLE
Intersect: behavior if only one source has the attribute:

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#290]
It's fine if just one of the two sources has a particular named tensor attribute: you just copy it over via the arc_map.  (Note: it can come from source a or b).  This works for attributes of all types.

If both sources have an attribute and it's an integer attribute, the behavior for now should be: check that the values are identical in all the pairs of arcs, and if so copy one of them; else die.    

https://github.com/k2-fsa/k2/blob/3363292e3b2d4554eee025d2950a4c4ac20b6c01/k2/python/k2/fsa_algo.py#L80

**Comment by csukuangfj** [comment]
The pullrequest #282  does exactly as you suggested except for integer tensors. Will fix it
https://github.com/k2-fsa/k2/blob/93f0b0d603286c4bd1cf1b0de532b24f25ab8cec/k2/python/k2/fsa_algo.py#L81-L91
