### ISSUE TITLE
Keeping array in lambda

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#298]
Here, I think it would be more elegant/efficient to keep the Region object in the lambda, since that's the thing we need to keep hold off.

https://github.com/k2-fsa/k2/blob/e527c3c9f1b2abd76be8b30d81ea164a71f1d534/k2/python/csrc/torch/torch_util.cu#L83

**Comment by csukuangfj** [comment]
Changed as you suggested in #282 

It saves only a few bytes. I don't think it will make a big difference.

**Comment by csukuangfj** [comment]
Closing via #282
