### ISSUE TITLE
sort arcs first on labels then on dest_state

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#301]
Guy, I know we have discussed this at https://github.com/k2-fsa/k2/pull/282#discussion_r513135550,  but I want to propose it here again: if we sort arcs first on labels then on dest_state, then for arc-sorted input Fsas of intersection, we will get arc-sorted output naturally; otherwise, we may need call `ArcSort` again after intersection. I'm not 100% sure if we can get benefit in other cases with this property, but I think it's worth doing this as it does not make a big difference from the perspective of sorting speed. Correct me if I'm wrong.

BTW, our implemetation of host arc-sorted and GPU arc-sorted (sorting on just labels) is not consitent now.

**Comment by danpovey** [comment]
I think it might be easier if we make the arc-sorting consistent by adding
sorting-on-dest-state to the GPU arc-sorting code.
The time difference will be tiny anyway.

**Comment by qindazhu** [comment]
OK, will do

**Comment by danpovey** [comment]
We could also at least add as a TODO, to use a sorting object that only
compares the label and dest-state, when arc-sorting host WFSAs.
Currently it compares all 3 but this is wasteful as within each range the
src-states are the same.

**Comment by qindazhu** [comment]
Seems you have removed `src_state`  in your last PR.
https://github.com/k2-fsa/k2/blob/f90888996dc9f75b537f7e8180d1aa64f7a3f6d6/k2/csrc/host/fsa.h#L59-L64

**Comment by qindazhu** [comment]
Will close this issue as it has been fixed with PR https://github.com/k2-fsa/k2/pull/302
