### ISSUE TITLE
Wrap dense intersection code

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#311]
Has anyone started work wrapping IntersectDensePruned to python?  I thought this was done but now don't see it.
This is one of the last pieces we need to get something working.

**Comment by csukuangfj** [comment]
I think this has already been wrapped. Please see

https://github.com/k2-fsa/k2/blob/325b2c3cdf43fc6378e0b1b2a8efff8e1e9f16a0/k2/python/csrc/torch/fsa_algo.cu#L139

and

https://github.com/k2-fsa/k2/blob/325b2c3cdf43fc6378e0b1b2a8efff8e1e9f16a0/k2/python/k2/autograd.py#L85

**Comment by danpovey** [comment]
Thanks!

**Comment by csukuangfj** [comment]
Closing via #309
