### ISSUE TITLE
Templates in tests

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#315]
Can we please avoid templating test code on the device type?
It's wasteful because none of the functions used are templated on it, it just ends up as a function arg used when creating the context.
Unless there is some benefit I can't see, such as producing clearer error messages.

**Comment by qindazhu** [comment]
Sure, for new tests now, we have already not used templating on device type, and for old tests code, let me remove them one by one (may be in a big PR, but not urgent)

**Comment by qindazhu** [comment]
Fixed in https://github.com/k2-fsa/k2/pull/397
