### ISSUE TITLE
Wrap Index()

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#317]
I added a new version of function Index(), that indexes axis 0 of a RaggedTensor.  This will be useful for the wake-word
task that @freewym is working on, to form the minibatch of FSAs used as supervision.

It would be nice if this could be wrapped to Python and made applicable to FSAs.

Note: there is also a version of Index() that takes an integer argument.  That should be wrapped too, if it isn't already, as it can be used for extracting one FSA from a vector of FSAs.

At some point we are going to have problems with name conflicts.  It might be a good idea to separate the functions operating on FSAs and ragged tensors (when we wrap them!) into separate Python modules k2.fsa and k2.ragged.   Let me know what you guys think about that.  But not urgent, I guess.  Right now I guess k2 and k2.fsa are effectively the same thing, as the FSA-related functions are in the k2 namespace.

**Comment by csukuangfj** [comment]
Will wrap it this night or tomorrow.

Sunday, 8 November 2020, 20:12 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by danpovey** [comment]
Great!  
The use-case is that for the wake-word task, we construct a k2.Fsa with 2 Fsas in it, one for non-wake-word and one for wake-word; and then to get the minibatch Fsa, we index that with a vector of zeros and ones.  It would be great if you could produce some test code that doesthat, for @freewym's benefit.

**Comment by csukuangfj** [comment]
> Note: there is also a version of Index() that takes an integer argument

It looks like this version lacks of output information for back propagation.

**Comment by danpovey** [comment]
The one that takes an integer argument always produces values that are a sub-range of the original values, so we don't need a vector to express the backprop info in this case.  The only information we might need is the offset in the original values array, which can be obtained from a difference of data pointers.

**Comment by csukuangfj** [comment]
I see. Will wrap it this night.

**Comment by freewym** [comment]
Is it possible to also wrap `fsa.union()`. I feel I need to do a union of all HMMs for monophones in my case to be composed with L.fst.

**Comment by csukuangfj** [comment]
> Is it possible to also wrap fsa.union()

Sure, will add it tomorrow after finishing this pullrequest.

**Comment by danpovey** [comment]
I don't think we have implemented union, yet?
Incidentally, the easiest way to implement it would be to let the
start-state of the result have epsilon transitions to the original start
states.   (The final-state wouldn't need this).  For some applications it
would be necessary to remove epsilons, or maybe determinize, afterward.
I can implement this, let me try to figure out the timeline, maybe today,
I'm not sure.

**Comment by qindazhu** [comment]
RE union, yes, we have not implemented it.
we also need to wrap host version of rm-epsilon and determinize, they have not been wrapped to python.

**Comment by csukuangfj** [comment]
I have been planning to implement `concat`. I think `union` is similar to `concat` and will implement both of them.

**Comment by csukuangfj** [comment]
> I can implement this, let me try to figure out the timeline, maybe today,
I'm not sure.

Well, will wait for your implementation if you have time.

**Comment by danpovey** [comment]
You can do it if you plan to do it in a GPU-compatible way.
