### ISSUE TITLE
build pip package automatically for dev purpose?

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#319]
@csukuangfj Can you kindly build a latest pip package with master branch? And wondering if there's any way we can create pip package automatically every day (or when master is updated), for dev purpose for now?

**Comment by csukuangfj** [comment]
Can you follow the instructions in
https://github.com/k2-fsa/k2/blob/f3d68a93d49feb9b66c9b7b9190d2c9142479f7a/scripts/build_pip.sh#L5-L30

> And wondering if there's any way we can create pip package automatically every day

Yes, it is possible provided that we have a GPU for CI, e.g. CircelCI.

**Comment by csukuangfj** [comment]
I just build a pip package for Python 3.6, with CUDA 10.1 on Ubuntu:

Please see https://pypi.org/project/k2/#files

**Comment by qindazhu** [comment]
OK，thanks, will do by following your instructions.

**Comment by csukuangfj** [comment]
Now you can use `pip install k2` to install the latest version (0.0.8).

**Comment by qindazhu** [comment]
I built a local version by following build_pip.sh as my python version is 3.8.

**Comment by csukuangfj** [comment]
There are versions for 3.6, 3.7 and 3.8 on PyPI.

**Comment by csukuangfj** [comment]
>  And wondering if there's any way we can create pip package automatically every day (or when master is updated), for dev purpose for now?

I think I've figured out how to build a k2 pip package with GitHub actions. Will create a pullrequest.

**Comment by qindazhu** [comment]
I will get the error when importing my local build `k2`
```
File "/ceph-hw/.local/lib/python3.8/site-packages/k2/ops.py", line 8, in <module>
    from .ragged import index as ragged_index
```
I guess submodule `ragged` is a private module in your design?

**Comment by csukuangfj** [comment]
> I will get the error when importing my local build k2

Please pull the latest master and try again. It should fix the problem.
