### ISSUE TITLE
Ragged __str__

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#328]
Fangjun, could you please add a `__str__` function to the pybind of the ragged objcts right away?
I need it for something I'm working on and debugging, and I'm not 100% sure how to do it.

**Comment by csukuangfj** [comment]
I am adding it.

**Comment by danpovey** [comment]
Thanks!!

**Comment by csukuangfj** [comment]
Added in #329 

You can find its usages in

https://github.com/k2-fsa/k2/blob/2b1ea4ecce3a0d95a3a1b70e5061cc01548ff573/k2/python/tests/fsa_test.py#L416-L428

**Comment by csukuangfj** [comment]
Closing via #329
