### ISSUE TITLE
Backward of get_tot_scores ignores gradient

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#341]
This is not right:
https://github.com/k2-fsa/k2/blob/59e7757c23e360acc5f655977683b2dfd8a3ce02/k2/python/k2/autograd.py#L55
the backward of get_tot_scores needs to multiply by the gradient at the output.
In our training, this is causing us to get the sign of the update wrong!!!

**Comment by danpovey** [comment]
This code isn't right but shows the general idea:
where backward() does:
```
    return None, None, None, arc_scores.exp()
```
we'll do something like this:
```
   arc_to_fsa_idx =  fsas.arcs.RowSplits(1)[fsas.arcs.RowSplits(2)]  # must change if this has 2 axes
   return None, None, None, arc_scores.exp() * tot_scores_deriv[arc_to_fsa_idx]
```

**Comment by csukuangfj** [comment]
Will fix it.
