### ISSUE TITLE
index_add_ replace

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#343]
At some point we should replace the index_add_ here, which requires conversion to int64, with our own index_add.
https://github.com/k2-fsa/k2/blob/c6d658ea71676e820e5fd883ff57ec5963acef19/k2/python/k2/autograd.py#L187
(Only after we've resolved the memory problem  in snowfall though.)

**Comment by galv** [comment]
@danpovey snowfall?

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/snowfall

**Comment by csukuangfj** [comment]
> At some point we should replace the index_add_ here,

`index_add_` is implemented in #327

**Comment by danpovey** [comment]
Thank.. you could perhaps try using it here as part of the testing of your
implementation of index_add.

**Comment by csukuangfj** [comment]
> you could perhaps try using it here as part of the testing of your
implementation of index_add.

Do you mean the backward propagation of `index_select`? 

Yes, I am using it.

**Comment by danpovey** [comment]
I think I might have been thinking about in autograd.py where index_add is
used.

**Comment by csukuangfj** [comment]
> I think I might have been thinking about in autograd.py where index_add is
used.

Yes, I have replaced  `torch.Tensor.index_add_` and `_k2.index_select_backward` with `_k2.index_add` in autograd.

**Comment by danpovey** [comment]
Resolved in #327
