### ISSUE TITLE
libc10.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by freewym** [k2-fsa/k2#349]
I checked out the latest k2 and follow the instruction in scripts/build_pip.sh to pip install the whl file into my python. But When I do `import k2` in my Python, it gives an error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/b03/ywang/anaconda3/lib/python3.8/site-packages/k2/__init__.py", line 1, in <module>
    from .autograd import get_tot_scores
  File "/export/b03/ywang/anaconda3/lib/python3.8/site-packages/k2/autograd.py", line 6, in <module>
    import _k2
ImportError: libc10.so: cannot open shared object file: No such file or directory

Do you have any clues on this problem? Thanks

**Comment by csukuangfj** [comment]
Did you `import torch` before `import _k2`?

```python
import torch
import _k2
```

**Comment by freewym** [comment]
OK. it is resolved.

**Comment by freewym** [comment]
Another error:

There is a SegFault when I wrote a very simple fst and was trying to load it as:
`s='''`
`0 0 0 1 -1.2`
`0 1 1 0 -4.2`
`1`
`'''`
` k2.Fsa.from_openfst(s, acceptor=False)`

Am I doing it correctly?

**Comment by csukuangfj** [comment]
```python
s='''
0 0 0 1 -1.2
0 1 -1 -1 -4.2
1
'''
```

Arcs entering the final state MUST have label == -1 and aux_label == -1

**Comment by csukuangfj** [comment]
@freewym 
Please use this pullrequest https://github.com/k2-fsa/k2/pull/348 for `union`.
There is a bug in the latest master branch.

**Comment by freewym** [comment]
> ```python
> s='''
> 0 0 0 1 -1.2
> 0 1 -1 -1 -4.2
> 1
> '''
> ```
> 
> Arcs entering the final state MUST have label == -1 and aux_label == -1

Bu I was calling `from_openfst()`. Does it also have such -1 constraint?

**Comment by csukuangfj** [comment]
```
>>> import torch
>>> import k2
>>> s='''
0 0 0 1 -1.2
0 1 1 0 -4.2
1
'''
>>> k2.Fsa.from_openfst(s, acceptor=False)

<k2.fsa.Fsa object at 0x7f6f6a95de50>
```

It works perfectly on my computer.

**Comment by csukuangfj** [comment]
> Bu I was calling from_openfst(). Does it also have such -1 constraint?

Oh, yes, you're right. k2 handles `openfst` format automatically.

**Comment by freewym** [comment]
Not sure whether it's relevant:  when I was doing cmake, there is some warnings like:

CMake Warning at k2/csrc/CMakeLists.txt:78 (add_executable):
  Cannot generate a safe runtime search path for target cu_ragged_test
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcufft.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcurand.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcublas.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libnvrtc.so.10.2] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libnvToolsExt.so.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcudart.so.10.2] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  k2/csrc/CMakeLists.txt:95 (k2_add_cuda_test)

CMake Warning at k2/csrc/CMakeLists.txt:78 (add_executable):
  Cannot generate a safe runtime search path for target cu_log_test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcufft.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcurand.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcublas.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libnvrtc.so.10.2] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libnvToolsExt.so.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib
    runtime library [libcudart.so.10.2] in /usr/local/cuda/lib64 may be hidden by files in:
      /export/b03/ywang/anaconda3/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  k2/csrc/CMakeLists.txt:95 (k2_add_cuda_test)

**Comment by csukuangfj** [comment]
Possible, but I'm not sure.

Can you use the prebuilt wheel packages? That is, `pip install k2==0.1` or download it from `https://github.com/k2-fsa/k2/actions/runs/364571745`.

**Comment by freewym** [comment]
> Possible, but I'm not sure.
> 
> Can you use the prebuilt wheel packages? That is, `pip install k2==0.1` or download it from https://github.com/k2-fsa/k2/actions/runs/364571745

have this error when import k2:

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /export/b03/ywang/anaconda3/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so)

**Comment by csukuangfj** [comment]
I just tried the two methods listed above. Both of them work.

I am not familiar with `anaconda` and not sure what happens on your system.

(1)
```
(py38) $ pip install k2-0.0.1.dev20201115-cp38-cp38-linux_x86_64.whl
Processing ./k2-0.0.1.dev20201115-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: graphviz in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from k2==0.0.1.dev20201115) (0.14.1)
Requirement already satisfied: torch in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from k2==0.0.1.dev20201115) (1.6.0+cu101)
Requirement already satisfied: future in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from torch->k2==0.0.1.dev20201115) (0.18.2)
Requirement already satisfied: numpy in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from torch->k2==0.0.1.dev20201115) (1.19.2)
Installing collected packages: k2
Successfully installed k2-0.0.1.dev20201115
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/xxx/py38/bin/python -m pip install --upgrade pip' command.
(py38) $ python -c "import torch; import k2"
```

(2)
```
(py38) $ pip uninstall k2
Found existing installation: k2 0.0.1.dev20201115
Uninstalling k2-0.0.1.dev20201115:
  Would remove:
    /xxx/py38/LICENSE
    /xxx/py38/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so
    /xxx/py38/lib/python3.8/site-packages/k2-0.0.1.dev20201115.dist-info/*
    /xxx/py38/lib/python3.8/site-packages/k2/*
    /xxx/py38/lib/python3.8/site-packages/libk2context.so
    /xxx/py38/lib/python3.8/site-packages/libk2fsa.so
Proceed (y/n)? y
  Successfully uninstalled k2-0.0.1.dev20201115
(py38) $ pip install k2==0.1
Collecting k2==0.1
  Downloading k2-0.1-py38-none-any.whl (6.2 MB)
     |████████████████████████████████| 6.2 MB 1.5 MB/s
Requirement already satisfied: graphviz in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from k2==0.1) (0.14.1)
Requirement already satisfied: torch in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from k2==0.1) (1.6.0+cu101)
Requirement already satisfied: numpy in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from torch->k2==0.1) (1.19.2)
Requirement already satisfied: future in /xxx/pyenv/versions/3.8.0/lib/python3.8/site-packages (from torch->k2==0.1) (0.18.2)
Installing collected packages: k2
Successfully installed k2-0.1
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/xxx/py38/bin/python -m pip install --upgrade pip' command.
(py38) $ python -c "import torch; import k2"
```

**Comment by freewym** [comment]
OK use a whl file built with ubuntu 16.04 solves the import issue

**Comment by csukuangfj** [comment]
great

**Comment by csukuangfj** [comment]
By the way, you can always find the prebuilt whl packages for every pullrequest on this page https://github.com/k2-fsa/k2/actions

**Comment by freewym** [comment]
But still SegFault...

**Comment by csukuangfj** [comment]
I tried it once again on this [colab notebook][1] and it works fine.

Can you use `gdb` to get some backtrace?

[1]: https://colab.research.google.com/drive/1T9RJ9WHvhgq1JdKJA1AHUgra4Kg0ynFs?usp=sharing

**Comment by freewym** [comment]
I was using the Python API. How can I use gdb for that?

**Comment by csukuangfj** [comment]
> I was using the Python API. How can I use gdb for that?

Please refer to https://wiki.python.org/moin/DebuggingWithGdb

I guess `pdb` also works.

**Comment by freewym** [comment]
Is it informative?

> <string>(1)<module>()
(Pdb) r
[New Thread 0x7fff76b16700 (LWP 21411)]
[New Thread 0x7fff76315700 (LWP 21412)]
[Thread 0x7fff76315700 (LWP 21412) exited]
[New Thread 0x7fff76315700 (LWP 21413)]
[New Thread 0x7fff75b14700 (LWP 21414)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

**Comment by danpovey** [comment]
And when it crashes in gdb you can use
(gdb) info sharedlibrary
to see what libraries are loaded, which may help..

**Comment by danpovey** [comment]
Not really, you should use gdb.
gdb --args python your_script.py
(gdb) r

**Comment by csukuangfj** [comment]
Can you build a debug version locally and run it again? I guess it will give you more information.

**Comment by freewym** [comment]
When built with the  Debug mode, there is no SegFault any more. But another issue: I have to reserve GPU on CLSP grid first (@danpovey ), otherwise my program was killed. Does it mean the fsa is actually created on GPUs?

**Comment by csukuangfj** [comment]
I guess so. `_k2.*.so` depends on libtorch cuda, which is loaded when we do `import _k2`.

Not sure whether libtorch cuda will   initalize the GPU while it is loaded.

**Comment by csukuangfj** [comment]
> Does it mean the fsa is actually created on GPUs?

The fsa is created on CPU.

**Comment by freewym** [comment]
> I guess so. `_k2.*.so` depends on libtorch cuda, which is loaded when we do `import _k2`.
> 
> Not sure whether libtorch cuda will initalize the GPU while it is loaded.

The program was killed when I called `from_openfst()`; it was not kill when `import k2`

**Comment by csukuangfj** [comment]
You need to have a GPU to run the code. Otherwise, it will abort.

https://github.com/k2-fsa/k2/blob/4c3c2a9428014ed24bd7abdca2e43ea50ac4c27e/k2/csrc/context.h#L174-L181

**Comment by danpovey** [comment]
I'm surprised.  I would have thought objects would be created on the CPU by
default, like in Torch.

**Comment by danpovey** [comment]
... if cudaMemcpy requires a device to be initialized for CPU->CPU
transfers then we should change that code.    I created an issue.

**Comment by csukuangfj** [comment]
@freewym 
Can you try this pullrequest https://github.com/k2-fsa/k2/pull/348

It should run on CPU.

**Comment by freewym** [comment]
> @freewym
> Can you try this pullrequest #348
> 
> It should run on CPU.

Problems solved.
