### ISSUE TITLE
nvtx

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#363]
Guys, in order to make the profiling easier we should add NVTX commands to the code.

http://developer.download.nvidia.com/NsightVisualStudio/2.2/Documentation/UserGuide/HTML/Content/NVTX_Library.htm

similar to what was done in some Kaldi code by the NVidia guys.  (you can git grep -i nvtx in kaldi code to see what they did).

I have figured out how to use nsys to profile our stuff, I'll share it with you to-morrow.  But it will be much more informative if we add NVTX to our code.  I don't know many details about it, I'm afraid.

**Comment by danpovey** [comment]
More details on the NVTX stuff:
The basic usage that we need is I think
```
  nvtxRangePush("some message");
   ...
   nvtxRangePop()
```
E.g.
```
  nvtxRangePush("Intersection");
   nvtxRangePop()
```
orjust:
```
  nvtxRangePush(__FUNCTION__);
   nvtxRangePop()
```
I think rather than calling that directly we should create a class that does this to avoid errors
when someone returns early, e.g.
```
   void some_func() {
      NvtxRange r(__FUNCTION__);
   }
```
 where NvtxRange is a class that does that push and pop stuff.
We can add this invocation  `  NvtxRange r(__FUNCTION__);` fairly liberally in most functions
 in the library.  We can also wrap a Python version of this object NvtxRange, so we can do the
 same kind of thing in Python functions (this will allow us to see where we are in the python-level
 processing, e.g. processing minibatches and so on).

 We may eventually decide to disable this in release mode (probably not for now though).

 We need to link with an extra library called libnvToolsExt.so, if we use this.  I am hoping that someone
 will volunteer to help

**Comment by csukuangfj** [comment]
I would like to do it. 

But I am out of office in the next few days. If it's urgent, other guys can take it.



Sent from myMail for iOS


Thursday, 19 November 2020, 11:36 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by csukuangfj** [comment]
working on it.
