### ISSUE TITLE
.to() for Ragged

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#367]
Can someone please add a to(device: torch.Device) function to class Ragged's binding code?
Need it for something, probably by to-morrow afternoon.

**Comment by csukuangfj** [comment]
> Can someone please add a to(device: torch.Device) function to class Ragged's binding code?

There is no Python class `Ragged`. Do you mean the C++ class?

**Comment by danpovey** [comment]
OK, well in Python it becomes RaggedArc, RaggedInt, but that template.

**Comment by csukuangfj** [comment]
There are `_k2.RaggedArc` and `_k2.RaggedInt`.

They have four methods:

https://github.com/k2-fsa/k2/blob/fbe3da9da882424d07b84098c0a45f9be3ac5bfd/k2/python/csrc/torch/ragged.cu#L27-L45

which are used by `Fsa.to_`:

https://github.com/k2-fsa/k2/blob/fbe3da9da882424d07b84098c0a45f9be3ac5bfd/k2/python/k2/fsa.py#L615-L624

**Comment by danpovey** [comment]
yeah but a single.function would be a lot.easier.
