### ISSUE TITLE
Bind RaggedShape

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#368]
At some point we are going to need bindings for classs RaggedShape.  Not urgent, just putting it up here so we don't forget.

**Comment by glynpu** [comment]
Seems it is not difficult. I would like to take this task.

Results from a draft solution: 

![image](https://user-images.githubusercontent.com/14951566/99878319-7b696a80-2c3f-11eb-92a5-7c19fed4ee5c.png)
