### ISSUE TITLE
Change license to Apache

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#371]
After some discussions here at Xiaomi we decided to change the license back to Apache (currently MIT).
They are very similar so hopefully this will be OK with all the contributors (fangjun, you should probably make sure that Lei Xin is OK with it though).

**Comment by qindazhu** [comment]
@csukuangfj @leixin @chenguoguo @mahsa7823 @freewym @Jarvan-Wang it's better if you can reply here directly so that we can make sure you notice this license change.

**Comment by freewym** [comment]
I'm OK with it.

**Comment by leixin** [comment]
LGTM

**Comment by csukuangfj** [comment]
Yes, Apache is fine with us.



Sent from myMail for iOS


Friday, 20 November 2020, 11:45 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by danpovey** [comment]
No-one objected; let's go ahead and do this.  The licenses are the same in spirit, anyway...

**Comment by songmeixu** [comment]
Close as solved.
