### ISSUE TITLE
Add NVTX_RANGE() thingies to lots of code

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#375]
I don't remember the details, look at the recently merged PR #369 where Fangjun added this macro.
Basically we want to add this liberally at the beginning of functions which will help us with diagnostics.
Since it's fairly easy perhaps would be a good one for @jimbozhang to start with?

**Comment by jimbozhang** [comment]
Yeah, I'm glad to do it.

**Comment by qindazhu** [comment]
Closed as we have finished this.
