### ISSUE TITLE
index issue of arc_map in host wrapper code

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#379]
As we call `Append` here for arc_map for those host wrapper functions, e.g. `Connect`, `Intersect`, the arc-id in the result arc_map is arc-idx2 instead of arc-idx012 (for FsaVec version). 
https://github.com/k2-fsa/k2/blob/8ee60447f3a1d347c72d222902800468c24a3315/k2/csrc/fsa_algo.cu#L47
We will get wrong answer when do `index_select`
https://github.com/k2-fsa/k2/blob/8ee60447f3a1d347c72d222902800468c24a3315/k2/python/k2/fsa_algo.py#L158-L159

I think we should change those index in arc_map to arc_idx012.

**Comment by danpovey** [comment]
arcs contain index2's, not ondex012's.

**Comment by danpovey** [comment]
oh sorry, you are talking about an arc_map, not arcs.

**Comment by qindazhu** [comment]
Fixed in https://github.com/k2-fsa/k2/pull/396.
