### ISSUE TITLE
Class Timer should support CPU as well as GPU

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#381]
Could make the constructor accept the ContextPtr, and work it out from that.

**Comment by danpovey** [comment]
... and the cudaStream should be used, too, in cudaEventCreate() and so on.  Otherwise we may get incorrect results sometimes.

**Comment by csukuangfj** [comment]
It's straightforward to get the cuda stream via a ContextPtr
https://github.com/k2-fsa/k2/blob/41495be5626a5e987f521ae4a16cda45267f4525/k2/csrc/context.h#L99

The problem is, how to use the stream on CPU?

`cudaEventCreate` requires a CUDA capable device, I think.

**Comment by danpovey** [comment]
having the stream pointer == -1 (kCudaStreamInvalid) just means there is no
GPU so you should use CPU.
It's a timer class.  GPUs are not the core thing.

**Comment by csukuangfj** [comment]
Did you mean that the Timer class should support both GPU and CPU. The implementation for CPU is not limited to
the `cuda**` APIs, instead it can use any relevant APIs.

**Comment by danpovey** [comment]
Yes.

**Comment by csukuangfj** [comment]
I see. Will fix it in the current pull request. It is easy.
