### ISSUE TITLE
Sort() needed.

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#405]
It would be nice if we had a Sort method that would work with Array1<T>.
I'm open minded on the interface.  Right now I just need it to sort int32_s, but I want the `argsort` output, i.e.
I need the order.  Perhaps someone can look at our underlying libraries' sort capabilities (e.g. moderngpu
and/or cub) and write something?
Right now my main concern is that it be done fast, I am not too picky on the details or the speed.

**Comment by csukuangfj** [comment]
I will implement it this night or tomorrow morning.

**Comment by danpovey** [comment]
Resolved in #406
