### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by lianrzh** [k2-fsa/k2#409]
I install k2 with pip, and try to import k2, the undefined symbol problem occur.
`
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/app/anaconda3/lib/python3.7/site-packages/k2/__init__.py", line 1, in <module>
    from .autograd import get_tot_scores
  File "/data/app/anaconda3/lib/python3.7/site-packages/k2/autograd.py", line 6, in <module>
    import _k2
ImportError: /data/app/anaconda3/lib/python3.7/site-packages/_k2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
`

**Comment by danpovey** [comment]
Check your torch version, torch.__version__.
Possibly that version of k2 was compiled for a different version of torch.

@csukuangfj can you tell him how to find the appropriate version of k2 for
his Torch and Cuda toolkit version?

**Comment by csukuangfj** [comment]
> Possibly that version of k2 was compiled for a different version of torch.

Yes, I think so. `pip install k2` installs a version that is compiled against torch==1.6.0+cu101.

I guess you are using torch==1.7.0.

Please download the wheel package from

https://github.com/k2-fsa/k2/actions?query=workflow%3Abuild

Please refer to https://github.com/k2-fsa/k2/blob/master/INSTALL.md  for more details

**Comment by csukuangfj** [comment]
After installing k2,

```bash
python3 -m k2.version
```

should tell you the information such as which PyTorch version and CUDA toolkit were used to build k2.

**Comment by qindazhu** [comment]
And if you are using conda, please check the parts of `conda` in our INSTALL.md, e.g. using

```
conda create -n k2 python=3.7
conda activate k2
conda install pytorch==1.6.0 cudatoolkit=10.1 -c pytorch
```
to install the packages, and then do `pip install k2`

**Comment by lianrzh** [comment]
@danpovey @csukuangfj @qindazhu Thank you for your advice. The problem has been solved.
