### ISSUE TITLE
Implement functions declared in #411

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#412]
.. and test!  Would be helpful for a new version of intersection code I am writing.

**Comment by qindazhu** [comment]
OK, will do.

**Comment by danpovey** [comment]
@qindazhu I think we can relax the constraint that the last element is zero, and just specify that it must be nonnegative.
The if-statement would then read: 
`  if (i+1 == dim || src[i+1] < src[i]).`

**Comment by qindazhu** [comment]
OK

**Comment by danpovey** [comment]
Mm, it looks like we have to decide whether the last element is zero or not, otherwise we can't get the
property InvertMonotonicDecreasing(InvertMonotonicDecreasing(x) == x, the size would mismatch.
(Also, with my modification, we'd need to have ans.Dim() == src[0], not src[0] + 1, and obviously
remove the final zeros from the examples in the comment).
Because I need it for a without-zero case, let's say all elements must be positive.

**Comment by qindazhu** [comment]
Implemented in https://github.com/k2-fsa/k2/pull/415, closed
