### ISSUE TITLE
Plus(), Minus(), Times()

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#416]
e.g. 
```
template <typename T>
 void Plus(Array1<T> &a, Array1<T> &c, Array1<T> *c);
```
that would just do c[i] = a[i] + b[i], and the same for Minus() and Times().
We could also create wrapper versions that accept 2 args, like:
```
  Array1<T> Plus(Array1<T> &a, Array1<T> &c);
```
These will occasionally be needed, and having them already implemented will save work.

**Comment by qindazhu** [comment]
Taking (will do tomorrow morning)

**Comment by qindazhu** [comment]
Done with https://github.com/k2-fsa/k2/pull/418, closed.
