### ISSUE TITLE
ParallelRunner

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#420]
I have a proposal for how to modify ParallelRunner so it doesn't do unnecessary work.

We give an extra arg to its NewStream() method, which will be a size_t (defaulting to 0) saying approximately
how much work we expect to be done in this new stream (expressed, say, as a number of elements to be processed).
If that is less than some threshold, which we'll have to tune, we won't create a new stream (just use 0 for the stream, say;
and modify CudaStreamOverride::Push/Pop to just return if stream == 0).

**Comment by danpovey** [comment]
... the reason I modified it to use the dummy was that I noticed creating streams and recording events was taking more time than I had anticipated.

**Comment by qindazhu** [comment]
I just didn't get the meaning to do this here..if cuda event is expensive, we may not need `ParallelRunner` stuff at all, so why do we need to provide `NewStream(size_t)`? (BTW, compared `NewStream(size_t)`, I like class `ParallelDummy` you written before, it's simple and straightforward)

**Comment by danpovey** [comment]
well ParallelDummy is not doing anything at all.  But there will be problem sizes where it makes sense to parallelize things with new CUDA streams.  It's about using them when appropriate.

**Comment by qindazhu** [comment]
OK, I suggest we update this when we really need it, for now, it seems we didn't get any benfit from `ParallelRunner` according to your experiment and performance profiling? BTW, I'm not sure how to decide the `threshold`.

**Comment by danpovey** [comment]
We'd tune it, could set it to eg 10k initially.
I'll still be writing code that will depend on that stuff.
At some point we need to write some speed-test programs that give us
numerical metrics we can optimize.

**Comment by qindazhu** [comment]
OK, will add this.

**Comment by qindazhu** [comment]
Seems we should not just return in `Push` when we return 0 in `NewStream`, we need to set `stream_override_ == 0` in `Push`; otherwise, when we call `context->GetCudaStream()` we may use previous pushed stream. Correct me if I'm wrong. (We can also set `stream_override_ = 0` in `Pop` without pop stack)

https://github.com/k2-fsa/k2/blob/d376902aa15f0835030d9cc4662e4a6840bf1b35/k2/csrc/context.h#L371-L376
https://github.com/k2-fsa/k2/blob/d376902aa15f0835030d9cc4662e4a6840bf1b35/k2/csrc/context.cu#L18-L27

**Comment by danpovey** [comment]
No, we want to use the previous pushed stream, otherwise the behavior won't
be correct.  The idea is that it should be a no-op if the stream is 0, it
should not affect anything.

**Comment by qindazhu** [comment]
Oh, you're right, thanks

**Comment by qindazhu** [comment]
Done with https://github.com/k2-fsa/k2/pull/422, closed
