### ISSUE TITLE
Way to avoid if/else

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#430]
Instead of doing: 
`  if (c->GetDeviceType()  == kCpu) {  loop; } else {  declare lambda; eval }`
I propose to do something like this:
```
#define EVAL(context, dim, lambda_name, ...)  \
    if (context->GetDeviceType() == kCpu) {
      auto lambda_name = [=] __VA_ARGS__;
      for (int32_t i = 0; i < dim; i++) lambda_name(i);
  } else {
      auto lambda_name = [=] __device__ __VA_ARGS__;
     EvalDevice(context, dim, lambda_name);
 }
```
which would be called as:
```
  EVAL(c, foo.dim, lambda_do_something, (int32_t i) -> void { code here; });
```

**Comment by danpovey** [comment]
Note: there can be line breaks in the invocation where it says `code here;`.
I believe this should work.  It should be faster than __host__ __device__ lambdas because the CPU  lambda can be inlined.

**Comment by danpovey** [comment]
.. and we'd need to wrap it in do { } while(0); in order to allow the trailing semicolon.

**Comment by qindazhu** [comment]
I prefer to use `if else` for now and refactor code when we need to support new platforms,e.g. arm, or we use OpenCL or Mace, etc. I'm just not sure if we can wrap code in all platforms in lambdas (maybe we need template or inheritance).

**Comment by danpovey** [comment]
A macro based solution is likely going to be what we need.  Maybe even one
where the code is passed in as a string.
If we can't use lambdas we'll likely need to create structs to pass in the
required variables.

**Comment by danpovey** [comment]
.. also an advantage of my proposal is that get away from __host__
__device__ lambdas; these lambdas are an experimental feature and they also
make it
impossible for the compiler to optimize code well for CPU.

**Comment by csukuangfj** [comment]
I am going to implement it if no one else is currently working on it.

**Comment by danpovey** [comment]
Cool!

**Comment by qindazhu** [comment]
With current approach (put lambda in a macro), for any build erros in lambda, the compiler will only give the line number where `K2_EVAL` locates, instead of the real line number in the lambda. This is a little annoying for long lambdas.

**Comment by danpovey** [comment]
Mm, that's annoying.  For debugging we can always have people use Eval()
instead of the macro.
