### ISSUE TITLE
-Wall problem

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#431]
This is from  @qijiaxing via wechat..

just let you know, when I compile with cuda 11, I got an error from nvcc: unknown option "-Wall"
It seems an issue from pytorch
To solve, one can follow this: https://github.com/traveller59/spconv/issues/69#issuecomment-631840313

**Comment by csukuangfj** [comment]
Which CMake version are you using @qijiaxing ?
Are you using the one from `apt-get install` or is it downloaded from https://cmake.org/download/ (e.g., https://github.com/Kitware/CMake/releases/download/v3.18.5/cmake-3.18.5-Linux-x86_64.sh ) ?

**Comment by csukuangfj** [comment]
I think I encountered this problem before with CMake 3.12. 

My solution was to download CMake 3.11 or 3.18 from https://cmake.org/download/

**Comment by qijiaxing** [comment]
> Which CMake version are you using @qijiaxing ?
> Are you using the one from `apt-get install` or is it downloaded from https://cmake.org/download/ (e.g., https://github.com/Kitware/CMake/releases/download/v3.18.5/cmake-3.18.5-Linux-x86_64.sh ) ?

I used cmake 3.14

**Comment by csukuangfj** [comment]
Are you using the pre-installed one from the system?

**Comment by csukuangfj** [comment]
This issue has once been reported in #196 by chenguoguo.

**Comment by csukuangfj** [comment]
This should be resolved by #660. Closing.
