### ISSUE TITLE
.to for DenseFsaVec

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#435]
Can someone please implement the Python binding of ".to" for DenseFsaVec, so it works with Torch devices?

**Comment by danpovey** [comment]
.. also it looks to me like the constructor of DenseFsaVec is not checking that the row_splits and scores are on the same device.  It should (maybe easiest to add in the C++)
I notice  test_dense_fsa_vec_cuda() in dense_fsa_vec_test.py seems to be constructing a DenseFsaVec with 2 different devices.

**Comment by csukuangfj** [comment]
I am implementing it now.

**Comment by danpovey** [comment]
I see my comment about the mismatch was wrong, the arg of DenseFsaVec at the python level is supposed to be on CPU.
