### ISSUE TITLE
Operation to compose maps

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#445]
There will be situations where two successive FSA operations give an arc_map that's a ragged tensor, and we need to compose the arc_maps.

Suppose we have:
```
  Ragged<int32_t> step1_arc_map = ... , step2_arc_map = ... ;
```
The elements of step2_arc_map are indexes into step1_arc_map. 
We'll compos them as follows:
```
Ragged<int32_t> ComposeArcMaps(Ragged<int32_t> &step1_arc_map, 
                                                              Ragged<int32_t> &step2_arc_map);
```
Implementation will be something like the following:
```
  Ragged<int32_t> step1_elements = step1_arc_map[step2_arc_map.values];
  RaggedShape ans_shape = RemoveAxis(
                                 ComposeRaggedShapes(step2_arc_map.shape,
                                                                           step1_elements.shape), 1);
  return Ragged<int32_t>(ans_shape, step1_elements.values);
```

**Comment by qindazhu** [comment]
Ah, you declare it here, will implement it,  as I need it in `RemoveEpsilonIterative`. 
Also @freewym , after talking with @danpovey , we found the unpruned version is non-trivial, I'm now working on a GPU algorithm proposed by Dan which is an iterative approach.

**Comment by freewym** [comment]
@qindazhu Actually what I need for now is remove-epsilon on only fsa.labels (not necessary on aux_labels). Then perhaps the unpruned determinization is more suitable for me (I intended to remove epsilon from the closure of union of several HMMs to obtain H, which is to be intersected with L in my case) (?)

**Comment by qindazhu** [comment]
wait, so in each HMMs, the epsilons are `blanks` instead of `epsilons`, right? (I mean, it may match blank of the nnet output), and you just want to remove the epsilon introduced by `closure`? if that's true, the un-pruned version will not work well for your case as it will remove epsilons in each HMMs as well

**Comment by danpovey** [comment]
I think he said he shifts the labels so no pdf-id is zero (and anyway he uses hmm-state-specific blank symbols).

@freewym bear in mind that our determinization does not remove epsilons.

**Comment by freewym** [comment]
I was planning to do H.labels+1 before removing epsilon

**Comment by freewym** [comment]
> I think he said he shifts the labels so no pdf-id is zero (and anyway he uses hmm-state-specific blank symbols).
> 
> @freewym bear in mind that our determinization does not remove epsilons.

OK, then I have to wait for `RemoveEpsilonIterative`

**Comment by qindazhu** [comment]
I just fell if `real epsilon` is introduced by `union/closure`, maybe a simpler soluntion for this is we just implement version of `union/closure` which not add `epsilon`, that would be much more efficient than RemoveEpsilonIterative. @danpovey , what do you think about this? (of course, we still need to implement `RemoveEpsilonIterative` for other usage in the future).

**Comment by danpovey** [comment]
Only one iteration of RemoveEpsilonIterative will be needed in practice.
My concern is there will be too many corner cases to get right, if we do it
by modifying union and closure.

**Comment by qindazhu** [comment]
OK, let me implement `RemoveEpsilonIterative` first (and then add no epsilon version of `union/closure` and tested with current implementation, for future usages, but no hurry)

**Comment by qindazhu** [comment]
Closed as I have implemented `ComposeArcMaps` with https://github.com/k2-fsa/k2/pull/458, we have other PR tracking `RemoveEpsilonIterative`.
