### ISSUE TITLE
Pinned memory allocator

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#451]
This is a change that could significantly reduce the latency of some operations.

In addition to the contexts returned by GetCpuContext() and GetCudaContext(), we need a 3rd type of context which would return pinned (page-locked) memory.  Call this function GetPinnedContext().
(We need to remove the member-function of the same name from class Context).

Internally, in the PyTorch case this could probably use `at::cuda::getPinnedMemoryAllocator();`
In the default case (not compiling with Torch), for now we can just have the call to GetPinnedContext() return the CPU context, unless there is an easy way to allocate pinned memory (and cache it), IDK about that moderngpu allocator we use.

These pinned context virtual classes  would return kCpu as device type, but we could add a virtual function IsPinned() to class Context that will return true if the allocator returns pinned memory (i.e. only for the pinned context type).

We will have to change the function MemoryCopy().  Currently it takes only one Context object as an arg.  That appears to be the destination context, although this was not documented, which is not good.  We can give it the src and dest Contexts.
In the case of host to device transfers, if the source is pinned memory we can do async copy.  (For device to host, for now we'll make the transfer always synchronous).

It might be easier if GetMemoryCopyKind() were to accept ContextPtr instead of Context (avoid the hassle of dereferencing); and MemoryCopy could also accept ContextPtr.  That will make the code a bit easier to read and more consistent.

**Comment by csukuangfj** [comment]
Will implement it.

> IDK about that moderngpu allocator we use.

Moderngpu uses `cudaMalloc`. That is  why we have `moderngpu_allocator.h` in `k2`.
https://github.com/moderngpu/moderngpu/blob/2b3985541c8e88a133769598c406c33ddde9d0a5/src/moderngpu/context.hxx#L71

```cpp
// standard_context_t is a trivial implementation of context_t. Users can
// derive this type to provide a custom allocator.

  // Alloc GPU memory.
  virtual void* alloc(size_t size, memory_space_t space) {
    void* p = nullptr;
    if(size) {
      cudaError_t result = (memory_space_device == space) ? 
        cudaMalloc(&p, size) :
        cudaMallocHost(&p, size);
      if(cudaSuccess != result) throw cuda_exception_t(result);
    }
    return p;    
  }

**Comment by danpovey** [comment]
Ah Ok cool, cudaMallocHost allocates pinned memory, so that makes it easy.

**Comment by csukuangfj** [comment]
According to the documentation of PyTorch, we have to modify our MemoryCopy to use the pinned memory allocated by
`at::cuda::getPinnedMemoryAllocator()`.

https://github.com/pytorch/pytorch/blob/5180caeeb49f8bdf1ec58e37a40e10691d0f4c92/aten/src/ATen/cuda/PinnedMemoryAllocator.cpp#L12
```cpp
at::Allocator* getPinnedMemoryAllocator() {
  auto state = globalContext().lazyInitCUDA();
  return state->cudaHostAllocator;
}
```

https://github.com/pytorch/pytorch/blob/5180caeeb49f8bdf1ec58e37a40e10691d0f4c92/aten/src/THC/THCGeneral.cpp#L44
```cpp
  if (!state->cudaHostAllocator) {
    state->cudaHostAllocator = getTHCCachingHostAllocator();
  }
```

https://github.com/pytorch/pytorch/blob/5180caeeb49f8bdf1ec58e37a40e10691d0f4c92/aten/src/THC/THCCachingHostAllocator.h#L10
```cpp
// A caching allocator for CUDA host allocations (pinned memory).
//
// This provides a drop-in replacement for THCudaHostAllocator, which re-uses
// freed pinned (page-locked) memory allocations. This avoids device
// synchronizations due to cudaFreeHost calls.
//
// To ensure correct behavior, THCCachingHostAllocator_recordEvent must be
// called anytime a pointer from this allocator is used in a cudaMemcpyAsync
// call between host and device. We implement this for storages and tensors in
// copy_from_cpu_async_ and copy_to_cpu_async_.
//
// Note that this allocator does not split larger allocations into smaller
// blocks, unlike the caching device allocator.
//
THC_API c10::Allocator* getTHCCachingHostAllocator(void);

// Records an event in the specified stream. The allocation 'ptr' will not be
// re-used until the event has occurred.
THC_API cudaError_t THCCachingHostAllocator_recordEvent(void *ptr, at::cuda::CUDAStream stream);
```

Pay attention to:
> // To ensure correct behavior, THCCachingHostAllocator_recordEvent must be
> // called anytime a pointer from this allocator is used in a cudaMemcpyAsync
> // call between host and device.

> // Records an event in the specified stream. The allocation 'ptr' will **not** be
> // re-used until the event has occurred.

And the following is an example of how `THCCachingHostAllocator_recordEvent` is used:
https://github.com/pytorch/pytorch/blob/5180caeeb49f8bdf1ec58e37a40e10691d0f4c92/aten/src/ATen/native/cuda/Copy.cu#L192
```cpp
  if (non_blocking) {
    AT_CUDA_CHECK(cudaMemcpyAsync(dst, src, nbytes, kind, stream));
    void* ptr = (dst_device == kCPU ? dst : src);
    AT_CUDA_CHECK(THCCachingHostAllocator_recordEvent(ptr, stream));
  } else {
``` 

I think we have to call `THCCachingHostAllocator_recordEvent` inside `MemoryCopy` of k2.
As we don't know where the context retuned by `GetPinnedContext` comes from, we have
to figure out whether we need to call `THCCachingHostAllocator_recordEvent` when using
`cudaMemcpyAsync`.

---

I am not sure what the consequence of the following statement in the above comment if `THCCachingHostAllocator_recordEvent` is no called where it should be.
> // The allocation 'ptr' will **not** be
> // re-used until the event has occurred.

**Comment by danpovey** [comment]
I think if we don't record the event, there is a danger that we will
accidentally overwrite that memory before the copy actually executes.

It might be necessary to extend the Context interface to add something
that's a wrapper for THCCachingHostAllocator_recordEvent(ptr, stream))
(and that records the event directly, for our default interface).

In our default one, we could maintain an internal buffer of deleted piece
of pinned memory with their events;
and we don't delete them until they add up to a certain amount of memory,
say 10kb, or to, say 1000 objects
(and when we do delete them, we wait for the events).

**Comment by csukuangfj** [comment]
> I think if we don't record the event, there is a danger that we will
accidentally overwrite that memory before the copy actually executes.

Yes, you're right. PyTorch does some caching of the allocated memory. When a block of memory is
freed, `cudaFreeHost` is not called. Instead, the block is put in a pool and can be reused in the next allocation.
So if we are doing any **asynchronous** operations on the memory block, we have to call `THCCachingHostAllocator_recordEvent`.
