### ISSUE TITLE
index_select optimization possible

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#478]
Don't do this just now as I am changing the code where it fails to print more debug info..
The way SimpleRaggedIndexSelect1D tests that each sub-list has only one nonzero element is via a reduction.
There is an easier way that also naturally gives the output.

It's:
  Initialize array `output` of size ragged_input.Dim0(); set it to zero.
  For each element of the ragged array:  if (element is nonzero) set `output[row_of_this_elem] = element` 

  For each element of the ragged array:  if (element is nonzero and  `output[row_of_this_elem] != element` ) there is an error.

Just letting you know it's an available programming pattern.

**Comment by danpovey** [comment]
MM sorry, just realized that's not quite right in case there are duplicate elements in a list, but you could replace `element` in the above with `element_index` and it would work correctly, except there is one more indexing operation to get the output; and you'd have to initialize the array with -1's for that to work.

**Comment by qindazhu** [comment]
Thanks, learned. BTW, just to confirm, These two loops are two differnet kenerls (one by one), right? (otherwise we may get a read-write mismatch on one kernel)
```
For each element of the ragged array: if (element is nonzero) set output[row_of_this_elem] = element

For each element of the ragged array: if (element is nonzero and output[row_of_this_elem] != element ) there is an error.
```
So there are three kenerls in total (another is init the array  with `-1`), the original approach has 3 kenerls as well, I guess the gain may come from drop `SumPerSublist`?

Anyway, learned a new pattern, thanks

**Comment by danpovey** [comment]
Yes, they need to be in different kernels.

There are other issues with SimpleRaggedIndexSelect.
 Firstly, I don't really like this kind of code to be in the torch/ directory- the core implementation code should be in csrc/.
But also it's unnecessarily complicated.  We can just index the tensor with the `values` of the ragged tensor, use that to construct a `Ragged<T>` object using the indexed elements, and then use a simpler operation like `Array1<T> SelectNonzeroElements(Ragged<T> &src);`

**Comment by danpovey** [comment]
I was changing that code but let me not try any more as they would just be overwritten.
I had been trying to make the error message more informative:
```
  const int32_t *counts_data = counts.Data();
  Array1<int32_t> status(context, 1, 0);
  int32_t *status_data = status.Data();
  K2_EVAL(
      context, counts.Dim(), lambda_check_status, (int32_t i)->void {
        if (counts_data[i] > 1) status_data[0] = 1 + i;
      });
  int32_t s = status[0];
  if (s != 0) {
    Ragged<int32_t> indexes_cpu = indexes.To(GetCpuContext());
    Array1<int32_t> row_ids = indexes.RowIds(1);
    K2_LOG(FATAL) << "There must be at most one non-zero "
        "element in src for any sub-list in indexes; sub-list "
                 << (s-1) << " has too many elements: "
                 << indexes.values.Arange(indexes.row_ids[s-1],
                                          indexes.row_ids[s]);
  }
#endif
```
but now I'm not getting an error at all in the determinization code.

**Comment by danpovey** [comment]
... oh I see, all that is inside 
`#if !defined(NDEBUG)`.
It should be called regardless, as the debug mode is to detect code errors; but user errors should be detected regardless.
In fact, in this case it probably makes sense to have the interface of SelectNonzeroElements() return an error status rather than just die.  We could stil print an error though, for now.

**Comment by qindazhu** [comment]
OK, will put it in csrc and detetect usres errors (together with the `SelectNonzeroElements` approach you mention above) later (after your any changes committed in case of conflicts)

**Comment by danpovey** [comment]
I decided not to commit those changes, you can do the change anytime.

**Comment by qindazhu** [comment]
OK, will do after remove epsilon stuff

**Comment by qindazhu** [comment]
Closed with https://github.com/k2-fsa/k2/pull/607
