### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#495]
Our requirements.txt currently reads:
clang-format==9.0.0
flake8==3.8.3
graphviz==0.14.1
yapf==0.27.0

... How many of these are really needed by users?  They seem like they are only needed for development and testing.
I don't want to make install difficult because of these requirements.

**Comment by pzelasko** [comment]
You can make it possible to pip install k2[dev] that pulls the optional dependencies like I did in Lhotse (I can commit that later).
