### ISSUE TITLE
Thread pool

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#529]
Currently, each time IntersectDensePruned() is called (with enough data) it creates a new thread.  Having new threads created instead of using threads from a thread pool is not only inefficient but also makes the nsys profile stats harder to view.  We should create some kind of thread pool.
I am thinking the size of the pool could be based on use: i.e. we create a new thread whenever one isn't already in the pool.
The destructor of the thread-pool object could cause any threads it holds to exit.

**Comment by csukuangfj** [comment]
> The destructor of the thread-pool object 

I have several doubts about the above statement:

- When and where is the object created?
- When and where is the object destructed?
- Is it a global object? If so, should we ever destruct it?
