### ISSUE TITLE
Using MultiSplit to implement GetTransposeReorder and index_add

### ISSUE THREAD

**Issue by qindazhu** [k2-fsa/k2#537]
Just noticed that  `MultiSplit` is the Op we looked for before to implement `GetTransposeReorder` and `index_add`. 

https://arxiv.org/pdf/1701.01189.pdf
https://escholarship.org/content/qt346486j8/qt346486j8_noSplash_809cc510bc8972320c14381b8beb056b.pdf?t=o7fir1

https://github.com/cudpp/cudpp implements this (@danpovey this is the library I mentioned before that has implemented hash table)

**Comment by danpovey** [comment]
Fantastic!  We should try it out.

**Comment by csukuangfj** [comment]
Is anyone currently working on it?

**Comment by qindazhu** [comment]
I guess no, I'm starting working on ` CoveringShape` stuff, you can go ahead with this.

**Comment by csukuangfj** [comment]
ok, I am going to implement it and then benchmark it.

**Comment by qindazhu** [comment]
Thanks.

**Comment by qindazhu** [comment]
BTW, I think we can also try hash table in cudpp for intersect stuff, it uses cuckoo hash tech, so maybe faster than our current one.

**Comment by csukuangfj** [comment]
Will do it.

**Comment by danpovey** [comment]
Guys, I don't think this is a good idea for the intersection actually, at least until we confirm that the hash table is currently a limiting factor.
Looking at their code it looks to me like some characteristics of the interface are not really what is needed.  It also might be a lot of complexity to take on board.

**Comment by danpovey** [comment]
... yeah, in fact because  their keys are limited to 32 bits my workaround for larger graphs and larger minibatch sizes wouldn't work.  I think this would be a lot of work with likely no gain.  Better to focus on other thigns, I think.

**Comment by qindazhu** [comment]
Back to the time I debug the training scripts, I just found there may be more than 100+ tries when insert/find, not sure if it still exists now.

**Comment by danpovey** [comment]
No, that was a bug that was fixed long ago.

**Comment by qindazhu** [comment]
Ah, OK, then I'm fine with not changing it, sorry for missing your changes about hash table.

**Comment by csukuangfj** [comment]
Closing via #571
