### ISSUE TITLE
normalize_scores

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#540]
We might want to implement certain Maximum Likelihood types of things, e.g. suppose in an LF-MMI/ASG-type scheme we want to train the scores of the denominator model to maximize the likelihood of the *numerator* after composition with it, so it's like a genuine language model.

In this case we'd need a function that normalizes a ragged tensor of scores, e.g. a `_k2.RaggedFloat == Ragged<float>`.  In fact, in order to implement the autograd correctly we probably want to break this up, by having the core function 
call LogSumPerSublist from k2/csrc/ragged_ops.h, and then the output would be the input minus the normalizer for the appropriate sub-list.  In the backprop, we'd have
`   input_deriv = output_deriv - exp(output.values) * repeat_out_deriv_sum`
where `repeat_out_deriv_sum` is obtained by doing SumPerSublist on `output_deriv` and then repeating the sum for this sub-list, for each element of the list.

I think all the core C++ code for this already exists, we just need to wrap `Ragged<float>` as `_k2.RaggedFloat` and wrap a few functions.  I recommend to create a file k2/ragged/autograd.py where we can put autograd things that don't pertain directly to FSAs.

The way we'd probably end up training these kinds of things is by having the un-normalized floating-point scores of the FSA be a tensor that lives with the model, and when doing the training forward pass we would compute the actual scores via something like`fsa.scores = k2.ragged.normalize_scores(_k2.Ragged(model.unnorm_scores, fsa.arcs.shape()))`
We could multiply by a small constant e.g. using `model.unnorm_scores * 0.1` if we encountered instability.

**Comment by csukuangfj** [comment]
Will work on it tomorrow. Currently, I am continuing with https://github.com/k2-fsa/snowfall/pull/57
