### ISSUE TITLE
intersect_dense does not support a_fsas.shape[0] == 1

### ISSUE THREAD

**Issue by freewym** [k2-fsa/k2#542]
The doc of `intersect_dense()` says `a_fsas.shape[0]`  can be 1:
https://github.com/k2-fsa/k2/blob/49e824afff691619637d68915ef4934cbec6153b/k2/python/k2/autograd.py#L419

But the underlying c++ seems to not allow it:

https://github.com/k2-fsa/k2/blob/bf274e6855b6e7efddfd3a5a91b5c75e193b4407/k2/csrc/intersect.cu#L108

and I got the check failure for that.

**Comment by qindazhu** [comment]
Seems @danpovey just copied the documentation of `intersect_pruned` back to that time. You can just use `intersect_pruned` for now (with large beam) or make two inputs have same dim. `intersect_pruned` was updated a lot by Dan these days, not sure if he wants to apply those changes to `intersect` or not (mainly to fix out of memory)

**Comment by csukuangfj** [comment]
I commented on it before, but got no response:

https://github.com/k2-fsa/k2/pull/427#discussion_r532393323

**Comment by csukuangfj** [comment]
The documentation is fixed in #544
