### ISSUE TITLE
Problems of converting an FSA from OpenFST to k2

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#560]
https://github.com/k2-fsa/snowfall/issues/60#issuecomment-752327748
shows that `G.fst` constructed by kaldi's arpa2fst gives worse WERs than the one created by [`egs/librispeech/asr/simple_v1/local/arpa2fst.py`][1]

I think the reason is that k2 assumes the start state is always 0, but G.fst created by kaldi's arpa2fst does
not satisfy this constraint.

So after converting `G.fst` to k2, some states are unreachable.

[1]: https://github.com/k2-fsa/snowfall/blob/master/egs/librispeech/asr/simple_v1/local/arpa2fst.py

---

For the following file `input.arpa`:
```
\data\
ngram 1=4
ngram 2=2
ngram 3=2

\1-grams:
-5.234679 a -3.3
-3.456783 b
0.0000000 <s> -2.5
-4.333333 </s>

\2-grams:
-1.45678 a b -3.23
-1.30490 <s> a -4.2

\3-grams:
-0.34958 <s> a b
-0.23940 a b </s>

\end\
```

```
$ ./open-source/kaldi/src/lmbin/arpa2fst input.arpa a.fst
./open-source/kaldi/src/lmbin/arpa2fst input.arpa a.fst
LOG (arpa2fst[5.5.1149~1-4df1f]:Read():arpa-file-parser.cc:94) Reading \data\ section.
LOG (arpa2fst[5.5.1149~1-4df1f]:Read():arpa-file-parser.cc:149) Reading \1-grams: section.
LOG (arpa2fst[5.5.1149~1-4df1f]:Read():arpa-file-parser.cc:149) Reading \2-grams: section.
LOG (arpa2fst[5.5.1149~1-4df1f]:Read():arpa-file-parser.cc:149) Reading \3-grams: section.
```

```
./open-source/kaldi/tools/openfst-1.6.7/bin/fstinfo a.fst
fst type                                          vector
arc type                                          standard
input symbol table                                a.fst
output symbol table                               a.fst
# of states                                       8
# of arcs                                         13
initial state                                     5
# of final states                                 1
```

After converting to `k2`, it is

<img width="877" alt="Screen Shot 2020-12-30 at 2 50 35 PM" src="https://user-images.githubusercontent.com/5284924/103334962-6e496200-4aae-11eb-8ba0-8e68de5b005a.png">

`k2` assumes that the start state is 0, but in openfst, the start state is 5.

---

We should change the code to handle this case. Since it is not possible to figure out the start state from
a string, should we let the user specify the start state while calling `k2.Fsa.from_openfst`?

**Comment by danpovey** [comment]
Yes, I think having the start state being optionally specified would make
sense.
In OpenFST it's done by having the 1st arc leave the start state, but that
conflicts with our requirements on sorting (not sure if we require the
OpenFST input to be sorted by src-arc).

**Comment by csukuangfj** [comment]
> In OpenFST it's done by having the 1st arc leave the start state, but that
conflicts with our requirements on sorting

Only format in k2 requires sorting the first column (though the documentation does not clarify this). In this case, can we also follow the convention in OpenFST,
taking the src state of the first arc as the start state?

**Comment by danpovey** [comment]
Yes I think that's OK.
Should clarify the requirement of the k2 format.

**Comment by danpovey** [comment]
Of course we'll need to clarify that if the start-state is not state 0, the
states will be renumbered to satisfy k2's requirements.
We could just swap state 0 and the start state.

**Comment by csukuangfj** [comment]
Will fix it.
