### ISSUE TITLE
Cannot import _k2 module in k2.egg

### ISSUE THREAD

**Issue by Jarvan-Wang** [k2-fsa/k2#570]
when import k2:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/k2-0.1.2+cu102.dev20210105-py3.7.egg/k2/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named '_k2'`
My solution is 
`(cd /search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/;unzip k2-0.1.2+cu102.dev20210105-py3.7.egg)`
But I don't know why

**Comment by csukuangfj** [comment]
How did you build and install k2?

**Comment by csukuangfj** [comment]
Did you follow https://github.com/k2-fsa/k2/blob/master/INSTALL.md?

**Comment by Jarvan-Wang** [comment]
solved after run ./scripts/build_pip.sh
