### ISSUE TITLE
Random number generation

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#578]
Would be nice to have a random number generation routine for CPU and GPU: something that can generate arrays of random numbers.  (Or I'm OK with other interfaces too).  We should probably make sure we can control the seed somehow.
Doesn't have to be the same between GPU and CPU.

Right now I am considering writing code that will select N paths from a distribution that's proportional to the scores on a lattice or other FSA (would require it to be top-sorted, probably).  This will need access to random numbers.  

Determinization is a little complex, so my current plan is to rely more on generating random paths, then figuring out the word sequences or phone sequences on the paths and de-duplicating them, and working mostly with those n-best lists and their compositions with the original un-determinized lattice.  Of course eventually I'll implement determinization, but I don't want to put it on the critical path any more than we have to.

**Comment by csukuangfj** [comment]
Working on the random number generator.

**Comment by csukuangfj** [comment]
Closing via #588
