### ISSUE TITLE
Docs: API reference doesn't render anything except headers

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#580]
See e.g.: https://k2.readthedocs.io/en/latest/python_api/dense_fsa.html

Screenshot:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/15930688/104242128-b06a9000-542c-11eb-8873-a585019d6063.png">

**Comment by csukuangfj** [comment]
fixed in #581

**Comment by csukuangfj** [comment]
readthedocs is still [building][1] the docs. Please wait for a few minutes and refresh the page again.

[1]: https://readthedocs.org/projects/k2/builds/12741819/

**Comment by csukuangfj** [comment]
It works now.
