### ISSUE TITLE
Mistake in BackpropGetArcPost

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#596]
This line
https://github.com/k2-fsa/k2/blob/53ffff8fc27973d84201fc6bbb58396b4deccb08/k2/csrc/fsa_utils.cu#L1216
isn't quite right... each arc-post takes the backward score from its ending state, so we need to sum over incoming arcs, i.e. sum `arc_post_deriv[incoming_arcs.values]` using `incoming_arcs.shape` (and not fsas.shape).

**Comment by danpovey** [comment]
While you're at it, I noticed some errors in my code which you could perhaps fix: `SumPerSublist(entering_arc_deriv, negative_infinity, &state_score_derivs);`, should be 0 not negative_infinity; 4 places.

**Comment by qindazhu** [comment]
Oh, yes, sorry for that mistake, will update in the next PR.

**Comment by qindazhu** [comment]
Sure, will also add tests and debug.

**Comment by qindazhu** [comment]
Closed with https://github.com/k2-fsa/k2/pull/597
