### ISSUE TITLE
Segmented ExclusiveSum

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#617]
This is an op I need for something: a segmented version of ExclusiveSum(), like a scan-not-reduce version of SumPerSublist().

**Comment by csukuangfj** [comment]
There is a segmented scan from cudpp: `cudppSegmentedScan`
http://cudpp.github.io/cudpp/2.0/group__public_interface.html#gaf71eb423ec3252ca122e5c01b055fa51

**Comment by csukuangfj** [comment]
I will try to implement it tomorrow if no one else wants to work on it.

**Comment by danpovey** [comment]
Great!
