### ISSUE TITLE
Publish wheel packages automatically

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/k2#658]
Currently, k2 is released to PyPI manually and it takes about 15 minutes for the process.
k2 on PyPI supports torch==1.7.1+cu101 with Python 3.6, 3.7, and 3.8.

What I would like to propose is that we do the release process automatically with GitHub actions:
- Reserve a specific branch. Whenever it is updated, e.g, merge from the master, it triggers GitHub actions to build wheel packages and publish them to PyPI
- Or trigger the actions whenever a new tag (i.e., release) is available. Since new versions are released less frequently, I prefer the first option.

One limitation of PyPI is that it imposes some constraint on the filename of the package. Consequently, we can
only support a single PyTorch version with each Python version. PyTorch's approach is to host their packages on
their own server and users use the `-f` option for `pip install` to specify the server from which to install it. For instance
```
pip install torch==1.2.0+cu92  -f https://download.pytorch.org/whl/torch_stable.html
```

@danpovey Can we also find a public server to host pre-built k2 packages? The advantages for such a server
are that users can download whatever versions that are suitable for them, like PyTorch.

I believe servers like `https://openslr.org/` should work. But maybe we need a different domain name.

**Comment by danpovey** [comment]
Sure, we can set that up, I'd have to get a domain name, perhaps k2-fsa.org?

**Comment by csukuangfj** [comment]
That would be great.

According to https://www.python.org/dev/peps/pep-0503/, I think all we need is to have a publicly accessible server and set up an HTML page with links to the pre-built packages stored on the server.

If all is set up, we can install k2 with

```
pip install k2==0.3.2+cu102 -f https://k2-fsa.org/whl/k2_stable.html

# or

pip install k2==0.3.2.dev20210205+cu101 -f https://k2-fsa.org/whl/nightly/cu101/k2_nightly.html
```
Just like how people would install `PyTorch`.

**Comment by csukuangfj** [comment]
Closing via #662 and #665
