### ISSUE TITLE
Online decoder

### ISSUE THREAD

**Issue by francisr** [k2-fsa/k2#671]
Hi,  

Is there a plan for k2 to have a decoder with a similar functionality to the kaldi online decoder, which supports endpointing and online determinization?  

Best regards,

**Comment by danpovey** [comment]
Eventually, but that might not happen for quite some time (at least a year).  Our aim in k2 right now is not to reproduce existing pipelines, but to try types of model that were not possible before.

**Comment by francisr** [comment]
Thanks.
