### ISSUE TITLE
GLIBC version 

### ISSUE THREAD

**Issue by tomkocse** [k2-fsa/k2#673]
Hi, 

I install k2 with the following procedures:

conda create -n k2 python=3.7
conda activate k2
conda install pytorch==1.6.0 cudatoolkit=10.2 -c pytorch

pip install k2==0.3.3+cu102.dev20210209 -f https://k2-fsa.org/nightly/

Then when I import k2, it reports an error that GLIBC_2.27 is required.

My GLIBC version is only 2.23. 

May I know if it is necessary to upgrade GLIBC to 2.27 for using k2?

Best regards,

**Comment by csukuangfj** [comment]
Does install k2 from source https://k2.readthedocs.io/en/latest/installation.html#install-k2-from-source
solve the problem?

**Comment by csukuangfj** [comment]
By the way, we have described the environment about building the wheels in the documentation https://k2.readthedocs.io/en/latest/installation.html#from-https-k2-fsa-org-nightly

> You can find a list of nightly built wheels at https://k2-fsa.org/nightly/. They are built using PyTorch 1.7.1 and support a combination of Python 3.6, 3.7, and 3.8 with CUDA 10.1, 10.2, and 11.0.

The prebuilt wheels are using PyTorch 1.7.1. I would recommend you to use
```
conda install pytorch==1.7.1 cudatoolkit=10.2 -c pytorch
```

It is recommended to always select the one with the most recent date from https://k2-fsa.org/nightly/ while installing.
For example, the latest k2 as of today is
```bash
pip install k2==0.3.3+cu102.dev20210302 -f https://k2-fsa.org/nightly/
```

---

I just tested the installation process with the latest anaconda https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh and it works perfectly. It does not need `sudo` permissions.

**Comment by tomkocse** [comment]
I have followed your instruction on installing k2 from pre-built wheel packages.
Still, it reports an error of not having GLIBC_2.27.
May I know if the platform you just tested is having GLIBC 2.27 ?

**Comment by csukuangfj** [comment]
This morning I used anaconda3-2020.11 with Ubuntu 18.04 to test the setup.

`conda info` prints

```
(myk2) fangjun:~$ conda info

     active environment : myk2
    active env location : /root/fangjun/software/anaconda3/2020.11/envs/myk2
            shell level : 1
       user config file : /root/fangjun/.condarc
 populated config files : /root/fangjun/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=10.2=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /root/fangjun/software/anaconda3/2020.11  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/fangjun/software/anaconda3/2020.11/pkgs
                          /root/fangjun/.conda/pkgs
       envs directories : /root/fangjun/software/anaconda3/2020.11/envs
                          /root/fangjun/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.9.2-3.0.0.std7b.el7.5.x86_64 ubuntu/18.04.5 glibc/2.27
                UID:GID : 1088:0
             netrc file : None
           offline mode : False
```

`python3 -m k2.version` prints
```
(myk2) fangjun:~$ python3 -m k2.version
Collecting environment information...

k2 version: 0.3.3
Build type: Release
Git SHA1: 9c3c1f64543b246af3c9e7288cfd01677954058c
Git date: Thu Feb 25 10:24:07 2021
Cuda used to build k2: 10.1
cuDNN used to build k2: 8.0.2
Python version used to build k2: 3.7
OS used to build k2: Ubuntu 18.04.5 LTS
CMake version: 3.19.5
GCC version: 7.5.0
CMAKE_CUDA_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0
PyTorch version used to build k2: 1.7.1+cu101
PyTorch is using Cuda: 10.1
NVTX enabled: True
Disable debug: True
Sync kernels : False
Disable checks: False

```

**Comment by tomkocse** [comment]
I use docker to create a virtual machine to run a Linux distribution with GLIBC 2.27. 
It works now.
I think it is better to state that GLIBC 2.27 is one of requirements for installing k2 from pre-built wheel packages.
