### ISSUE TITLE
Put the docs URL in GitHub

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#697]
Currently, the K2 docs can be a little hard to discover. GitHub has a special "featured spot" for project websites where you could put the link to https://k2.readthedocs.io/en/latest/

see e.g.:

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/15930688/112379720-e2b32c00-8cbe-11eb-92ab-e81fe4eac527.png">

**Comment by csukuangfj** [comment]
I believe only Dan has the permission to edit that.

**Comment by danpovey** [comment]
Done
