### ISSUE TITLE
[suggestion] conda install k2

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#733]
Several people asked me about the solution to issues with incompatible GLIBC version after they `pip install k2` (typically systems older than Ubuntu 18.04, on which the pip packages are being built). I always tell them to compile from source and I even prepared a [GitHub gist for that](https://gist.github.com/pzelasko/c5c84a27a9107c27c40ff3d43a28526b) (apparently when you install it in conda env, we need to add some more flags/setup to make it work, at least on the systems I worked with).

I understand it might be a larger effort, but maybe it's worth considering to build a conda package that uses anaconda-supplied compilers etc. -- this way people could actually `conda install k2` and avoid potential headaches.

**Comment by galv** [comment]
Ubuntu 16.04 uses glibc 2.23, while centos7 uses glibc 2.17. My impression is that building k2 on the centos7 machine at https://github.com/pypa/manylinux is a good approach to solving your problem. I'm not sure if it's better or worse than conda, though, with which I am less familiar. I will repeat this quote from the manylinux repo, though:

> Building manylinux-compatible wheels is not trivial; as a general rule, binaries built on one Linux distro will only work on other Linux distros that are the same age or newer. Therefore, if we want to make binaries that run on most Linux distros, we have to use an old enough distro.

@pzelasko do you know of people successfully building against older glibc and libstdc++ versions via conda?

**Comment by pzelasko** [comment]
I believe that anaconda provides its own build tool chain including gcc and glibc. This seems to be relevant: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=glibc

However, although I used it extensively for a long time, I’ve never built an anaconda package before, so I wouldn’t know all the details. 

Re manylinux - good idea, I didn’t know about it. CentOS7 is fairly old and has an older tool chain than Ubuntu 16 (gcc 4.8 vs 5.5 I think). I don’t know if it can handle k2 compilation though. I’m mostly supporting CLSP students and colleagues than can handle source compilation with some help, but I think it might be a deterrent for larger audience that just wants to use the library.

**Comment by jtrmal** [comment]
yes, conda has it's own toolchain.
manylinux I've been also using in the past works pretty well for binary
distribution.
y.

**Comment by csukuangfj** [comment]
k2 depends on PyTorch. I tried to build a manylinux wheel a few months ago within a docker but failed. I don't remember the exact error message, but it has something to do with PyTorch.

PyTorch provides manylinux pre-built wheels for some of its versions. But later PyTorch stops providing manylinux wheels.

The main obstacle to build a manylinux wheel for k2 is its dependency on PyTorch.

**Comment by galv** [comment]
> But later PyTorch stops providing manylinux wheels.

@csukuangfj can you provide a link to a github issue about this? I would like to learn more. Internally at NVIDIA, there is strong interest in using pypi if possible so I would like to learn more.

**Comment by csukuangfj** [comment]
@galv 
I have not found a GitHub issue about this.

You can find a list of pre-built wheels of  PyTorch from
https://download.pytorch.org/whl/torch_stable.html

You can see that the last PyTorch version supporting manylinux on x86 platform is torch 1.2.0 with CUDA 9.2.
After that, you cannot find any manylinux versions of PyTorch. I don't know the reason behind it.

**Comment by galv** [comment]
I think there may be a confusion here.

For example, there's a torch-1.8.0 build with cuda 11.1 here if you search for this string:

"cu111/torch-1.8.0%2Bcu111-cp36-cp36m-linux_x86_64.whl"

My impression is that they dropped the phrase "manylinux" because it's not possible to make pytorch to conform to some part of the manylinux spec (e.g., cuda must be statically linked rather than dynamically linked, I believe).

**Comment by csukuangfj** [comment]
@galv 

I just found that PyTorch provides manylinux docker images with different CUDA versions.
See http://docker.pytorch.org/docker_hub.html.

Will look into it when I have time.

**Comment by csukuangfj** [comment]
> @csukuangfj can you provide a link to a github issue about this? I would like to learn more. Internally at NVIDIA, there is strong interest in using pypi if possible so I would like to learn more.

@galv 
I tried to use one of the docker images from http://docker.pytorch.org/docker_hub.html to build k2, but the resulting
wheel cannot be repaired by `auditwheel`. It produces the following message:
```
$ auditwheel repair --plat manylinux1_x86_64 ./k2-0.3.4.dev20210514-py3-none-any.whl
INFO:auditwheel.main_repair:Repairing k2-0.3.4.dev20210514-py3-none-any.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "./k2-0.3.4.dev20210514-py3-none-any.whl" to "manylinux1_x86_64" ABI because of the presence of too-re
cent versioned symbols. You'll need to compile the wheel on an older toolchain.

$ auditwheel show ./k2-0.3.4.dev20210514-py3-none-any.whl

k2-0.3.4.dev20210514-py3-none-any.whl is consistent with the following
platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libnvToolsExt.so.1 with versions
{'libnvToolsExt.so.1'}, libm.so.6 with versions {'GLIBC_2.2.5'},
libgcc_s.so.1 with versions {'GCC_3.0'}, libcudart.so.10.1 with
versions {'libcudart.so.10.1'}, libc.so.6 with versions
{'GLIBC_2.2.5', 'GLIBC_2.3', 'GLIBC_2.3.3', 'GLIBC_2.4', 'GLIBC_2.14',
'GLIBC_2.7', 'GLIBC_2.3.2'}, libstdc++.so.6 with versions
{'GLIBCXX_3.4.14', 'CXXABI_1.3.3', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4',
'CXXABI_1.3.7', 'CXXABI_1.3', 'CXXABI_1.3.2', 'GLIBCXX_3.4.5',
'GLIBCXX_3.4.18', 'CXXABI_1.3.5', 'GLIBCXX_3.4.17'}, libdl.so.2 with
versions {'GLIBC_2.2.5'}, librt.so.1 with versions {'GLIBC_2.2.5'},
libpthread.so.0 with versions {'GLIBC_2.3.2', 'GLIBC_2.2.5'}

This constrains the platform tag to "manylinux_2_17_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```

---

I also checked the manylinux wheel provided by PyTorch from PyPI:

```
# go to https://pypi.org/project/torch/1.8.1/#files
$ wget https://files.pythonhosted.org/packages/dd/b9/824df420f6abf551e41bbaacbaa0be8321dc104f9f3803051513844dc310/torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl

$ auditwheel show torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl

torch-1.8.1-cp36-cp36m-manylinux1_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: librt.so.1 with versions
{'GLIBC_2.2.5'}, libgcc_s.so.1 with versions {'GCC_3.0', 'GCC_4.2.0',
'GCC_3.3', 'GCC_3.4'}, libm.so.6 with versions {'GLIBC_2.2.5'},
libpthread.so.0 with versions {'GLIBC_2.3.4', 'GLIBC_2.3.3',
'GLIBC_2.3.2', 'GLIBC_2.2.5', 'GLIBC_2.12'}, libgomp-a34b3233.so.1
with versions {'OMP_1.0', 'GOMP_4.0', 'GOMP_1.0'}, libstdc++.so.6 with
versions {'GLIBCXX_3.4.11', 'CXXABI_1.3', 'GLIBCXX_3.4.18',
'GLIBCXX_3.4.9', 'CXXABI_1.3.5', 'CXXABI_1.3.7', 'GLIBCXX_3.4.19',
'GLIBCXX_3.4.14', 'GLIBCXX_3.4.13', 'GLIBCXX_3.4.17', 'CXXABI_1.3.2',
'GLIBCXX_3.4.5', 'CXXABI_1.3.1', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4',
'CXXABI_1.3.3'}, libdl.so.2 with versions {'GLIBC_2.2.5'}, libc.so.6
with versions {'GLIBC_2.14', 'GLIBC_2.3.4', 'GLIBC_2.3',
'GLIBC_2.3.2', 'GLIBC_2.6', 'GLIBC_2.11', 'GLIBC_2.10', 'GLIBC_2.4',
'GLIBC_2.9', 'GLIBC_2.2.5', 'GLIBC_2.17', 'GLIBC_2.3.3', 'GLIBC_2.7',
'GLIBC_2.15', 'GLIBC_2.16'}, libcudart-80664282.so.10.2 with versions
{'libcudart.so.10.2'}, libnvrtc-08c4863f.so.10.2 with versions
{'libnvrtc.so.10.2'}, libnvToolsExt-3965bdd0.so.1 with versions
{'libnvToolsExt.so.1'}

This constrains the platform tag to "manylinux_2_17_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
```

Someone in this post [The next manylinux specification](https://discuss.python.org/t/the-next-manylinux-specification/1043/11) says
> After all, Tensorflow and PyTorch have been pushing rogue wheels because “it works for their users”.

The following google group disscussion[TensorFlow, PyTorch, and manylinux1](https://groups.google.com/a/tensorflow.org/g/developers/c/TMqRaT-H2bI) says
> TensorFlow and PyTorch unfortunately don’t produce manylinux compatible wheels. The challenge is due, at least in part, to the need to use nvidia-docker to build GPU binaries [10].

You can find some of your NVIDIA colleagues mentioned in the above discussion, e.g, see https://groups.google.com/a/tensorflow.org/g/build/c/WgtWKA4t_bs . I believe they can share more information
about this with you.

There is still an open issue in PyTorch for building manylinux wheels: https://github.com/pytorch/pytorch/issues/15294

---

Hope the above links help.
