### ISSUE TITLE
k2.intersect_dense_pruned fails with illegal memory access when used in multi-GPU training

### ISSUE THREAD

**Issue by GNroy** [k2-fsa/k2#745]
I'm trying to train an MMI-MBR model in a multi-GPU setup in NeMo (the multi-GPU training is powered by pytorch-lightning).

The issue is that `k2.intersect_dense_pruned` works just fine in a single GPU but fails in a two-GPU setup with
```
[F] /k2/k2/csrc/array.h:329:T k2::Array1<T>::operator[](int32_t) const [with T = int; int32_t = int] Check failed: ret == cudaSuccess (700 vs. 0)  Error: an illegal memory access was encountered.
[ Stack-Trace: ]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2_log.so(k2::internal::GetStackTrace[abi:cxx11](
)+0x58) [0x7efe8266e3c8]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2context.so(k2::Array1<int>::operator[](int) con
st+0x76a) [0x7efe8278507a]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2context.so(k2::Renumbering::ComputeOld2New()+0x
1b9) [0x7efe82780c99]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2context.so(k2::MultiGraphDenseIntersectPruned::
PruneTimeRange(int, int)+0x2c65) [0x7efe829550f5]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2context.so(std::_Function_handler<void (), k2::
MultiGraphDenseIntersectPruned::Intersect()::{lambda()#1}>::_M_invoke(std::_Any_data const&)+0x197) [0x7efe82955d77]
/opt/conda/lib/python3.8/site-packages/k2-0.3.4.dev20210518+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/libk2context.so(k2::ThreadPool::ProcessTasks()+0x18b
) [0x7efe82ac765b]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6d84) [0x7eff631b7d84]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7eff82b2d609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7eff82a54293]
```
The error is thrown by a process that is on the second GPU.

My software setup:

- Docker image `nvcr.io/nvidia/pytorch:21.03-py3` (python 3.8, cuda 11.2, torch 1.9.0a0)
- k2 from commit `6326266a1a242901449767a00a08b3e8cb4dc6e9`

**Comment by csukuangfj** [comment]
> the multi-GPU training is powered by pytorch-lightning)

Did you make any changes to the code in snowfall to support multi-gpu training? 

If any, is it possible to show us the changes?

**Comment by danpovey** [comment]
It looks like it may be necessary to make changes like those described here
https://discuss.pytorch.org/t/c-cuda-extension-with-multiple-gpus/91241/6
e.g. in all of our wrappers where our code is called from PyTorch.

**Comment by GNroy** [comment]
> > the multi-GPU training is powered by pytorch-lightning)
> 
> Did you make any changes to the code in snowfall to support multi-gpu training?

No, unfortunately. I'm trying to implement MMI and MBR losses in Nvidia NeMo toolkit (since I'm an intern at Nvidia). It uses Pytorch Lightning trainer to train on multiple GPUs and nodes.
I'm sorry not being of help with snowfall.

**Comment by csukuangfj** [comment]
@GNroy 
I am trying to fix k2 for multi-gpu training. Please wait for a while until I am done.
