### ISSUE TITLE
Use HLG or unigram as P of den_graph, got -inf score

### ISSUE THREAD

**Issue by Jarvan-Wang** [k2-fsa/k2#764]
When I try to avoid the int32 overflow issue of char level model, I try:
1, compose a small HLG graph (got by compile_HLG) rather than HP;
2, use unigram P;
     the code is 
```
def create_unigram_phone_lm(phones: List[int]) -> k2.Fsa:
    assert 0 not in phones
    final_state = len(phones) + 1
    rules = ''
    for i in range(1, final_state):
        rules += f'0 {i} {phones[i-1]} 0.0\n'
    for i in range(1, final_state):
        rules += f'{i} {final_state} -1 0.0\n'
    rules += f'{final_state}'
    return k2.Fsa.from_str(rules)
```
but the score of den_graph is both -inf
Any idea?

**Comment by csukuangfj** [comment]
I think your unigram P is not correct. There should only two states. State 0 has as many self loops as the number of phones.

**Comment by csukuangfj** [comment]
There is a new ctc_topo, called build_ctc_topo2. Could you try that?

**Comment by Jarvan-Wang** [comment]
> 
> 
> I think your unigram P is not correct. There should be only two states. State 0 has as many self loops as the number of phones.

It works, but why?

**Comment by csukuangfj** [comment]
> It works

Can you explain what do you mean by `it works`?

**Comment by Jarvan-Wang** [comment]
> 
> 
> > It works
> 
> Can you explain what do you mean by `it works`?

The score and loss goes to normal
