### ISSUE TITLE
Why aren't FSA operations templated on the semiring type?

### ISSUE THREAD

**Issue by galv** [k2-fsa/k2#765]
There is something I've been wondering as I've been digging into K2 more.

In openfst, each FST algorithm would depend upon the Weight of your input Fsts, either directly or indirectly. (Normally, you access the weight via Fst::Arc::Weight). This Weight would define Times, Plus, Zero, One, and so on for the particular semiring you're using. For example, here Times() is called in openfst's composition implementation: https://github.com/mjansche/openfst/blob/5be570c4e84a5eae1325d8c6c43fdbba3683863e/src/include/fst/compose.h#L389

Meanwhile, we appear to assume the log-semiring here (from what I can tell) in IntersectDense: https://github.com/k2-fsa/k2/blob/dd3da2a9a4db06a6404234e9bf8892112d454a21/k2/csrc/intersect_dense.cu#L780

Why is this? In particular, this is a bit surprising to me since your choice of semiring during composition, etc. does influence how your ultimate FST looks. I understand that you can choose between log and tropical semirings in get_forward_scores() and get_total_score, but that doesn't allow you to, e.g., do pruned intersection in the tropical semiring. Doing pruned intersection in the tropical semiring seems much closer to traditional ASR decoding than doing pruned intersection in the log semiring in my opinion.

**Comment by danpovey** [comment]
No, it's assuming tropical, there is no LogAdd() in that code.

For many of the algorithms, log and tropical semirings look the same.  For algorithms, where they are not the same, generally speaking the interface would be a bit different so we have separate versions of the code.  Or if the algorithm is the same, it's a boolean argument.

**Comment by galv** [comment]
Yes, you're right that we cannot straightforwardly use generic code for many of these algorithms. I see that intersection is using the "argmax trick" with 64-bit integers.
