### ISSUE TITLE
`sum` interface

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#805]
The sum_per_sublist function for ragged lists in k2 only supports float; I'd like it to also support int32.
Incidentally, I wonder whether it might be more torch-like to just call it `sum`, and have the axis specifiable, defaulting
to -1.  And to also have a class-member version of it.  So it could be called as k2.ragged.sum(ragged_array).
Of course this would have to fail, right now, for axis == 0, for instance.  But in future we might implement that case also.

**Comment by danpovey** [comment]
actually, it looks like it's very easy to extend sum_per_sublist to also support int32.  Would you mind doing that right away (@pkufool ) so I can work on top of it?  Need it for something.

**Comment by pkufool** [comment]
Sorry, I did not see this notification yestorday.  Currently, let's fix this by simply adding `sum_per_sublist` function for int32. I am wrapping _k2 ragged functions as class member for RaggedInt and RaggedFloat,  will post in another pull request, in that change, let's adapt all the interface more torch-like.

**Comment by pkufool** [comment]
Closed by https://github.com/k2-fsa/k2/pull/812.
