### ISSUE TITLE
'.to()' for ragged tensors

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#806]
Can we please have the '.to()' of ragged tensors support changing dtype, not just device?  For now it would just support changing float and int32, later this may change.
This is low priority though.

**Comment by csukuangfj** [comment]
Yes, it's doable. Will add it soon.

**Comment by danpovey** [comment]
thanks!

**Comment by pkufool** [comment]
Closed by https://github.com/k2-fsa/k2/pull/812.
