### ISSUE TITLE
k2 readthedocs does not exist now?

### ISSUE THREAD

**Issue by arctanx999** [k2-fsa/k2#824]
https://k2.readthedocs.io/en/latest/core_concepts/index.html  does not exist now? But I can get access to it several days ago.

**Comment by csukuangfj** [comment]
Please ue https://k2-fsa.github.io/k2/

We are using GitHub actions to build the doc and host it on GitHub pages.

We have updated it on the project home page
<img width="1340" alt="Screen Shot 2021-09-13 at 8 40 17 PM" src="https://user-images.githubusercontent.com/5284924/133085151-1ae49695-feda-4881-8bf0-f4177224b973.png">
.

**Comment by csukuangfj** [comment]
By the way, we have changed the interface for `k2.ragged`. It is more readable than before and there are lots of usage examples for each API.

Please have a look at https://k2-fsa.github.io/k2/python_api/api.html#k2-ragged

<img width="1059" alt="Screen Shot 2021-09-13 at 8 43 25 PM" src="https://user-images.githubusercontent.com/5284924/133085590-35c083c1-af54-48c2-b2d7-2571a2bca6af.png">

**Comment by csukuangfj** [comment]
I just placed a redirection link in https://k2.readthedocs.io/en/latest/

![Screen Shot 2021-09-13 at 22 32 08](https://user-images.githubusercontent.com/5284924/133102824-b223643f-1027-4b49-95d8-b4efadf2dc2d.png)

**Comment by arctanx999** [comment]
> Please use https://k2-fsa.github.io/k2/
> 
> We are using GitHub actions to build the doc and host it on GitHub pages.
> 
> We have updated the doc link on the project home page
> <img alt="Screen Shot 2021-09-13 at 8 40 17 PM" width="1340" src="https://user-images.githubusercontent.com/5284924/133085151-1ae49695-feda-4881-8bf0-f4177224b973.png">
> .

thx~bro
