### ISSUE TITLE
ImportError in k2 v1.9

### ISSUE THREAD

**Issue by GNroy** [k2-fsa/k2#834]
I'm getting `ImportError` when importing k2 on tag 1.9
```
>>> import k2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/k2-1.9.dev20210927+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/__init__.py", line 2, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: arg(): could not convert default argument into a Python object (type not registered yet?). Compile in debug mode for more information.
```
The import works with k2 on tag 1.8
upd: I'm installing k2 from source with `python3 setup.py install`

**Comment by csukuangfj** [comment]
By the way, I am using pip, not conda.

**Comment by GNroy** [comment]
@csukuangfj, thanks for your suggestions!
I did `python3 setup.py clean` before installation, but it didn't help.
Though I managed to make k2 v1.9 work properly in a clean pytorch container, so this weird issue was with my environment after all. Maybe some residual info stuck somewhere in the env (though I didn't detect any).
Anyway, I'm fine with the workaround. I'll close the issue.

**Comment by csukuangfj** [comment]
Happy to hear that you get k2 v1.9 work.

**Comment by csukuangfj** [comment]
> I did python3 setup.py clean before installation, but it didn't help.

Maybe you can use
```
rm -rf build/
pip uninstall k2
```

**Comment by GNroy** [comment]
> Maybe you can use
> 
> ```
> rm -rf build/
> pip uninstall k2
> ```
Thanks! Unfortunately, this didn't help either. The same `ImportError`.

**Comment by csukuangfj** [comment]
> > Maybe you can use
> > ```
> > rm -rf build/
> > pip uninstall k2
> > ```
> 
> Thanks! Unfortunately, this didn't help either. The same `ImportError`.

Ok. I don't know the reason for your error.

I am using the approach described in https://k2-fsa.github.io/k2/installation/for_developers.html
to install k2.

You can keep several versions of k2 in a single virtual environment just by changing the `PYTHONPATH` variable.

**Comment by GNroy** [comment]
> I am using the approach described in https://k2-fsa.github.io/k2/installation/for_developers.html to install k2.

I built the debug version of k2 v1.9. The error has slightly changed:
```
$ python3 -c "import k2; print(k2.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/k2/k2/python/k2/__init__.py", line 2, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: arg(): could not convert default argument 'device: c10::Device' in method '<class '_k2.ragged.RaggedTensor'>.__init__' into a Python object (type not registered yet?)
```
It looks like the issue is related to the pytorch device problem (as in https://github.com/k2-fsa/k2/issues/835).
Anyway, it doesn't cause much inconvenience, so it should be fine to leave this issue be.
