### ISSUE TITLE
Installing K2 would still automatically install torch 1.7

### ISSUE THREAD

**Issue by JinZr** [k2-fsa/k2#884]
I think K2 should be supporting torch==1.10 now, then why does it install torch 1.7 automatically?

**Comment by csukuangfj** [comment]
I believe you are installing k2 from PyPI via `pip install`.

There is one limitation using PyPI, which requires that the name of the uploaded file has to be in a fixed format  e.g., `k2-1.11-py38-none-any.whl `. 

As k2 is compiled against a specific version of PyTorch, we have been choosing torch 1.7.1 for the pre-built wheels hosted on PyPI.

---

If you want to use a different version of PyTorch with k2, you can select one of the following methods to install k2:

- (1) Use `conda install`  to install k2

- (2) Compile k2 from source

- (3) Manually download the pre-built wheels by GitHub actions and use `pip install` to install the downloaded file. Please see https://github.com/k2-fsa/k2/issues/854#issuecomment-952499135

**Comment by JinZr** [comment]
Thanks a lot! I'm closing this thread now.
