### ISSUE TITLE
cannot compile on Mac and new-ish cmake

### ISSUE THREAD

**Issue by jtrmal** [k2-fsa/k2#889]
```
$ cmake -DCMAKE_BUILD_TYPE=Release -DK2_WITH_CUDA=OFF  ..
CMake Error at /usr/local/Cellar/cmake/3.22.0/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:179 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
Call Stack (most recent call first):
  CMakeLists.txt:14 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/Users/jtrmal/projects/k2/build_release/CMakeFiles/CMakeOutput.log".
See also "/Users/jtrmal/projects/k2/build_release/CMakeFiles/CMakeError.log".
```

This is cause by unconditional specification of CUDA as a programming language of the project in CMakeLists.txt
Additionally, even after removing that specification, I will get an error later on in cmake processing

```
CMake Warning (dev) at /usr/local/Cellar/cmake/3.22.0/share/cmake/Modules/CMakeDependentOption.cmake:84 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  build_release/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Python executable: /usr/local/bin/python3.9
-- PyTorch version: 1.8.1
-- PyTorch cuda version: None
CMake Error at cmake/torch.cmake:48 (set_property):
  set_property could not find TARGET torch_cuda.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:170 (include)


```

**Comment by csukuangfj** [comment]
> Call Stack (most recent call first):
  CMakeLists.txt:14 (project)

Line 14 from the master is
https://github.com/k2-fsa/k2/blob/2cb3eeaa49b61d23f2917e5cb23ca03ef8ca709d/CMakeLists.txt#L14

---

> Call Stack (most recent call first):
  CMakeLists.txt:170 (include)

Line 170 from the master is
https://github.com/k2-fsa/k2/blob/2cb3eeaa49b61d23f2917e5cb23ca03ef8ca709d/CMakeLists.txt#L170


---

> CMake Error at cmake/torch.cmake:48 (set_property):

Line 48 from the master is
https://github.com/k2-fsa/k2/blob/2cb3eeaa49b61d23f2917e5cb23ca03ef8ca709d/cmake/torch.cmake#L48

---

Could you check that you are using the latest k2?

I see that you have specified `-DK2_WITH_CUDA=OFF`, so it should disable CUDA support and will not require NVCC to be installed.

**Comment by jtrmal** [comment]
I'm an idiot, was fetching from older master/main
SORRY!

**Comment by jtrmal** [comment]
I'm an idiot, closing
