### ISSUE TITLE
Unstack

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#898]
We already have a Stack() function; for the RNN-T decoding,  we will need its opposite.
Could call it Unstack(), the same as TensorFlow (it is unbind() in PyTorch).
The separated arrays should be separately allocated (this will allow memory to be released in a more granular way).

**Comment by pkufool** [comment]
I am going to implement it.

**Comment by pkufool** [comment]
Closed via https://github.com/k2-fsa/k2/pull/920
