### ISSUE TITLE
No module named _k2

### ISSUE THREAD

**Issue by kkasra12** [k2-fsa/k2#930]
I have freshly installed python3.8 and windows 10.
after running `pip install k2` and importing it in python(`import k2`), I faced this error:
```
Traceback (most recent call last):
  File "C:\Users\violet\AppData\Local\Programs\Python\Python38\lib\site-packages\k2\__init__.py", line 3, in <module>
    from _k2 import DeterminizeWeightPushingType
ModuleNotFoundError: No module named '_k2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\violet\AppData\Local\Programs\Python\Python38\lib\site-packages\k2\__init__.py", line 8, in <module>
    raise ImportError(
ImportError: No module named '_k2'
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH
```

let me know if you need more information

Thank you so much for your attention and participation.

**Comment by csukuangfj** [comment]
Please refer to https://github.com/k2-fsa/k2/issues/893#issuecomment-1002309532 to install k2 on Windows.

Note: It does not support CUDA on windows at present.

**Comment by csukuangfj** [comment]
If you are using Linux or macOS, you can use `pip install k2` to install `k2`. Otherwise, you have to  download the pre-built wheels from https://k2-fsa.org/nightly/index.html
