### ISSUE TITLE
ImportError on colab

### ISSUE THREAD

**Issue by HalflingWizard** [k2-fsa/k2#963]
It seems google has upgraded CUDA version used in colab; which causes an `ImportError `when I try to import k2.
even the official setup colab doesn't work anymore. the error reads:
`ImportError: k2 was built using CUDA 10.1
But you are using CUDA 10.2 to run it.`

Please address this issue. 
Thanks.

**Comment by csukuangfj** [comment]
Please see https://colab.research.google.com/drive/1mx9IU0C1xPl6XV1KWRRsUab2uDfx4FwK?usp=sharing

You can still use k2 in Colab notebook with its default settings.

You have to install `torch` and `k2` at the same time using
```python3
! pip install torch==1.7.1+cu101 k2 -f https://download.pytorch.org/whl/torch_stable.html
```

It won't work if you install them separately.

**Comment by HalflingWizard** [comment]
Thanks
