### ISSUE TITLE
Streaming decoding in rnnt_demo

### ISSUE THREAD

**Issue by ilya-edrenkin** [k2-fsa/k2#971]
Thanks for the awesome work!

I want to clarify my understanding of `rnnt_demo`. There is a comment saying "we are not using a streaming model currently": https://github.com/k2-fsa/k2/blob/v2.0-pre/k2/torch/bin/rnnt_demo.cu#L219

As far as I can understand the RNN-T model is kind of "naturally" streaming due to its autoregressive nature. Is there anything left to be done to enable streaming recognition using RNN-T with k2?

**Comment by csukuangfj** [comment]
We are using a non-streaming conformer model as the encoder network. That is why it is not streaming.

**Comment by ilya-edrenkin** [comment]
Thanks! Makes perfect sense. So simply using an encoder that would not be looking too much into the future should solve the problem completely?

**Comment by csukuangfj** [comment]
> Thanks! Makes perfect sense. So simply using an encoder that would not be looking too much into the future should solve the problem completely?

Yes, I believe so.

**Comment by ilya-edrenkin** [comment]
Thanks once again!
