### ISSUE TITLE
/home/runner/work/k2/k2/k2/csrc/device_guard.h:66:static int32_t k2::DeviceGuard::GetDevice() Don't call me

### ISSUE THREAD

**Issue by fightingtang** [k2-fsa/k2#977]
[F] /home/runner/work/k2/k2/k2/csrc/device_guard.h:66:static int32_t k2::DeviceGuard::GetDevice() Don't call me
[ Stack-Trace: ]
/mnt/data/home/work/anaconda3/envs/k2/lib/python3.8/site-packages/libk2_log.so(k2::internal::GetStackTrace()+0x47) [0x7fc239cdd1a7]
/mnt/data/home/work/anaconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0xdc4ba) [0x7fc23a4454ba]
/mnt/data/home/work/anaconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0x6bafa) [0x7fc23a3d4afa]
/mnt/data/home/work/anaconda3/envs/k2/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so(+0x1b9c3) [0x7fc23a3849c3]
python3(+0x13c00e) [0x55e5f671400e]
python3(_PyObject_MakeTpCall+0x3bf) [0x55e5f670913f]
python3(+0x166ca0) [0x55e5f673eca0]
python3(_PyEval_EvalFrameDefault+0x4f83) [0x55e5f67b3923]
python3(_PyFunction_Vectorcall+0x1b7) [0x55e5f67a57e7]
python3(+0x166b2e) [0x55e5f673eb2e]
python3(_PyEval_EvalFrameDefault+0x4f83) [0x55e5f67b3923]
python3(_PyEval_EvalCodeWithName+0x260) [0x55e5f67a4600]
python3(_PyFunction_Vectorcall+0x594) [0x55e5f67a5bc4]
python3(+0x1b97da) [0x55e5f67917da]
python3(_PyObject_MakeTpCall+0x228) [0x55e5f6708fa8]
python3(_PyEval_EvalFrameDefault+0x546a) [0x55e5f67b3e0a]
python3(_PyEval_EvalCodeWithName+0x260) [0x55e5f67a4600]
python3(_PyFunction_Vectorcall+0x594) [0x55e5f67a5bc4]
python3(_PyEval_EvalFrameDefault+0x1510) [0x55e5f67afeb0]
python3(_PyFunction_Vectorcall+0x1b7) [0x55e5f67a57e7]
python3(_PyEval_EvalFrameDefault+0x71b) [0x55e5f67af0bb]
python3(_PyEval_EvalCodeWithName+0x260) [0x55e5f67a4600]
python3(PyEval_EvalCode+0x23) [0x55e5f67a5eb3]
python3(+0x242622) [0x55e5f681a622]
python3(+0x2531d2) [0x55e5f682b1d2]
python3(+0x25636b) [0x55e5f682e36b]
python3(PyRun_SimpleFileExFlags+0x1bf) [0x55e5f682e54f]
python3(Py_RunMain+0x3a9) [0x55e5f682ea29]
python3(Py_BytesMain+0x39) [0x55e5f682ec29]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fc2a9585c87]
python3(+0x1f9ad7) [0x55e5f67d1ad7]

Traceback (most recent call last):
  File "./tdnn/train.py", line 577, in <module>
    main()
  File "./tdnn/train.py", line 573, in main
    run(rank=0, world_size=1, args=args)
  File "./tdnn/train.py", line 499, in run
    graph_compiler = CtcTrainingGraphCompiler(lexicon=lexicon, device=device)
  File "/data/home/tjq/k2/icefall/icefall/graph_compiler.py", line 43, in __init__
    L_inv = lexicon.L_inv.to(device)
  File "/mnt/data/home/work/anaconda3/envs/k2/lib/python3.8/site-packages/k2/fsa.py", line 1105, in to
    ans = Fsa(self.arcs.to(device), properties=self.properties)
RuntimeError:
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful:

      gdb --args python /path/to/your/code.py
****

**Comment by csukuangfj** [comment]
How did you install k2?

It seems that you are installed a CPU version of k2 but you try to use it with CUDA.

**Comment by fightingtang** [comment]
Thank you. I got it,I pip the cpu version.
