### ISSUE TITLE
Wrong intersection result after renaming labels

### ISSUE THREAD

**Issue by GNroy** [k2-fsa/k2#978]
Hi,

I use the latest (1.5.1) k2 release.

I've found severe mismatch between intersection (with `treat_epsilons_specially=False`) results if some of the labels are changed.

Say, if we intersect FSAs `a` and `b`, then the result will be correct.
But if we do `a.labels[a.labels == x] = y` and `b.labels[b.labels == x] = y` before the intersection, then the result will be different and therefore wrong.

The attached notebook contains steps to reproduce the issue (and a workaround I came up with):

[intersection_mismatch.ipynb.txt](https://github.com/k2-fsa/k2/files/8779032/intersection_mismatch.ipynb.txt) (remove the .txt)

**Comment by csukuangfj** [comment]
> But if we do a.labels[a.labels == x] = y and b.labels[b.labels == x] = y before the intersection, then the result will be different and therefore wrong.

Could you use
```
a.labels[a.labels == x] = y
a.__dict__["_properties"] = None

b.labels[b.labels == x] = y
b.__dict__["_properties"] = None
```
and see it it helps?

**Comment by csukuangfj** [comment]
Note: The following link to the Colab notebook is to simplify the process to view the provided `intersection_mismatch.ipynb.txt`

https://colab.research.google.com/drive/1mlNo6soSBxmY_GCNVjudIiITZjLqxU_g?usp=sharing

**Comment by csukuangfj** [comment]
> Though we still need to do k2.arc_sort for this to work on CPU.

Yes, you still need to arc sort them if you are doing intersection on CPU, as described in the doc:
https://k2-fsa.github.io/k2/python_api/api.html#k2.intersect

> The two input FSAs MUST be arc sorted if treat_epsilons_specially is True.

https://github.com/k2-fsa/k2/blob/ecfe7bd6d9189964bf3ff043038918d889a43185/k2/python/k2/fsa_algo.py#L279-L281

---

> Setting {a,b}.__dict__["_properties"] = None helped!

Please see https://github.com/k2-fsa/k2/issues/874#issuecomment-969974902
We have had such an issue before. I think we don't have much to do in k2 to detect this problem automatically.

**Comment by GNroy** [comment]
Ok, thanks for the explanation!

One last question: is it safe to set  `.__dict__["_properties"] = None`?
I mean, could it potentially break something?

**Comment by danpovey** [comment]
It's safe, just resets the properties to say they are unknown.
The difficulty with setting them automatically is that when you do:
` a.labels[a.labels == x] = y`
as far as `a` is concerned you are just accessing the labels, you are not assigning to them, so it has
no way to tell that you are changing something.

**Comment by csukuangfj** [comment]
> One last question: is it safe to set .__dict__["_properties"] = None?
I mean, could it potentially break something?

It is perfectly safe and won't break anything.

Setting it to `None` means the FSA's property is not initialized. When the property is needed, k2 will compute it and cache it for later use.

**Comment by GNroy** [comment]
@csukuangfj Thanks again!
Closing the issue.
