### ISSUE TITLE
Can I build k2 on arm64 platform ?

### ISSUE THREAD

**Issue by arthurwu4work** [k2-fsa/k2#979]
Hi everyone,

Can I build k2 on arm64 platform ?
I use pip install k2 to install k2 package and require torch==1.7.1
But torch only support the version over 1.8.0 for arm64 platform (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)(https://download.pytorch.org/whl/torch_stable.html)

Is there any solution to solve this problem ?

os : debian9

thank you

**Comment by csukuangfj** [comment]
Have you tried to build k2 from source?

**Comment by arthurwu4work** [comment]
oh, It works!!

thank you !!!
