### ISSUE TITLE
a valid Fsa in the OpenFst format

### ISSUE THREAD

**Issue by wwx007121** [k2-fsa/k2#985]
I want to load a TLG by k2.fsa, but it occurs an error,
ValueError: The following is not a valid Fsa in the OpenFst format (with num_aux_labels=0): 0   0   1   0
0   1   9   0   5.49121
0   2   30  0   2.76855
0   3   31  0   4.01074
0   4   32  0   3.7168
0   5   33  0   2.65234
0   6   39  0   3.47656
0   7   59  0   4.02051
0   8   60  0   3.10254
0   9   61  0   3.44336
0   10  92  0   2.45996
0   11  124 0   2.59082
0   12  125 0   4.34082
0   13  126 0   3.5459
0   14  127 0   3.85742
0   15  128 0   4.06934
0   16  139 0   7.72168
...
but，I think it‘ a standard format.

**Comment by wwx007121** [comment]
version: k2-1.15.1.dev20220616+cpu.torch1.8.1-py3.8-linux-x86_64.egg

**Comment by csukuangfj** [comment]
Can you post the code you are using for loading?

**Comment by csukuangfj** [comment]
Please change
```python3
self.k2_fsa = k2.Fsa.from_openfst(self.decode_fst)
```


to
```python3
self.k2_fsa = k2.Fsa.from_openfst(self.decode_fst, acceptor=False)
```

You can refer to the help information of `k2.Fsa.from_openfst` for its usage:
https://k2-fsa.github.io/k2/python_api/api.html#from-openfst

**Comment by wwx007121** [comment]
> Please change
> 
> ```python
> self.k2_fsa = k2.Fsa.from_openfst(self.decode_fst)
> ```
> 
> to
> 
> ```python
> self.k2_fsa = k2.Fsa.from_openfst(self.decode_fst, acceptor=False)
> ```
> 
> You can refer to the help information of `k2.Fsa.from_openfst` for its usage: https://k2-fsa.github.io/k2/python_api/api.html#from-openfst

code is changed, but also an error occurs
I've removed try from python code

TypeError: fsa_from_str(): incompatible function arguments. The following argument types are supported:
    1. (s: str, num_extra_labels: int = 0, num_ragged_labels: int, openfst: bool = False) -> Tuple[k2::Ragged<k2::Arc>, Optional[at::Tensor], List[k2::RaggedAny]]

Invoked with: <vector Fst at 0x7fccdf2436b0>, 1, 0; kwargs: openfst=True

**Comment by csukuangfj** [comment]
Please also change
```
self.decode_fst = fst.Fst.read(self.decode_fst_file)
```

It supports only FST from OpenFST in text format.
You can find example usage in https://github.com/k2-fsa/icefall/blob/5379c8e9fa13f6f2364b4a0db89fa3074266fb58/egs/librispeech/ASR/local/compile_hlg.py#L74

```python3
        with open("data/lm/G_3_gram.fst.txt") as f:
            G = k2.Fsa.from_openfst(f.read(), acceptor=False)
```

**Comment by wwx007121** [comment]
thx, problem is solved
