### ISSUE TITLE
About fas

### ISSUE THREAD

**Issue by wwx007121** [k2-fsa/k2#986]
"""
The final state has the largest state number. There is ONLY ONE final state. All arcs that are connected to the final state have label -1. If there are aux_labels, they are also -1 for arcs entering the final state.
"""
Is it means that I could only load the T,L,G, and compose them in order, but not load the TLG that is already composed by openfst, caused  by ONLY ONE final state allowed to set
or the final state is the virtual state added

**Comment by csukuangfj** [comment]
No, you can load FST in OpenFST format that has many final states.
During loading, k2 creates a new final state and makes all final states from OpenFST point to the newly created final state.

**Comment by wwx007121** [comment]
thx

**Comment by csukuangfj** [comment]
You can read
https://k2-fsa.github.io/k2/core_concepts/index.html#a-simple-fsa-example
to get more help.
