### ISSUE TITLE
prune_on_arc_post for Cyclic Graphs

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/k2#992]
Hi, 

I am experimenting with a lexicon that allows words with zero pronunciation to exist, meaning that certain words are emitted with epsilon input. Based on the output words, I trained a simple n-gram language model. 

Then, following the gist of compile_hlg.py, I composed the lexicon graph with the simple n-gram grammar graph, then determinised and removed epsilon from the resulting graph. As is expected, this yielded many grammatically nonsensical arcs with sub -30 posteriors. 

Is there a way to prune away those low-probability arcs? I tried prune_on_arc_post, but I think because my Grammar graph is cyclic, I am getting this error. 

> Check failed: dest_state > state_idx01

Otherwise, my resulting language model works as expected, both on CPU and GPU.

**Comment by danpovey** [comment]
prune_on_arc_post requires the input to be cycle-free, although this doesn't seem to be well documented.  It's intended for use on lattices.
for doing things with grammar graphs (or other static graphs), it may be better to use OpenFst utilities.  @csukuangfj what do you think would be the easiest way to do that, e.g. in terms of accessibility from python?

**Comment by csukuangfj** [comment]
> for doing things with grammar graphs (or other static graphs), it may be better to use OpenFst utilities. @csukuangfj what do you think would be the easiest way to do that, e.g. in terms of accessibility from python?

I can think of two ways:

(1) Recommended as you can get direct and immediate support from us.

Use https://github.com/csukuangfj/kaldifst

It does not have much documentation yet, but I am adding it.

(2) Use https://www.openfst.org/twiki/bin/view/FST/PythonExtension

**Comment by teowenshen** [comment]
Thank you for your recommendations!

I actually went ahead to change my algorithm and avoid producing those sub -30 arcs in the first place, since it was hinted that at the moment there is no way to do this within k2. I just left the ticket open to see what are some methods recommended for this task. 

I will close this ticket now.
