### ISSUE TITLE
Can't install from source

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/k2#994]
I am trying to install k2 from source starting from tritonserver image. Below is my dockerfile.

With  docker build . -f Dockerfile -t triton_k2:latest, the [log.txt](https://github.com/k2-fsa/k2/files/9024615/log.txt) is normal. However, when I test using python3 -m k2.version, it reports no module named k2.version. Also, I could only import k2 under workspace in the container, with only  few attributes available.

![Capture](https://user-images.githubusercontent.com/28823245/176812490-eb306234-f406-4d35-b1b6-72e247d9fb80.PNG)

Any help is appreciated. Thanks.

```
FROM nvcr.io/nvidia/tritonserver:22.05-py3
LABEL repository="tritonserver-k2"

RUN apt-get update && apt-get -y install python3-dev && apt-get install -y cmake && apt-get -y install libsndfile1
RUN pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

WORKDIR /workspace

# "sed -i ..."  line tries to turn off the cuda version check
# since env is cuda 11.6, however, can't find torch version compiled with CUDA 11.6

RUN git clone https://github.com/k2-fsa/k2.git && \
    cd k2 && \
    sed -i 's/FATAL_ERROR/STATUS/g' cmake/torch.cmake && \
    python3 setup.py install && \
    cd -
```

**Comment by danpovey** [comment]
when you run from workspace, it is just picking up the k2 directory I
think, it is not really installed.
I assume it would have shown some errors when you tried to do setup.py
install inside k2/.

**Comment by csukuangfj** [comment]
From the log,

> Installed /usr/lib/python3.8/site-packages/k2-1.16.dev20220630+cuda11.0.torch1.7.1-py3.8-linux-x86_64.egg

Can you find k2 in the above directory? If so, can you switch to that directory and run `python3 -m k2.version`?

**Comment by yuekaizhang** [comment]
> From the log,
> 
> > Installed /usr/lib/python3.8/site-packages/k2-1.16.dev20220630+cuda11.0.torch1.7.1-py3.8-linux-x86_64.egg
> 
> Can you find k2 in the above directory? If so, can you switch to that directory and run `python3 -m k2.version`?
Switch to /usr/lib/python3.8/site-packages/k2-1.16.dev20220630+cuda11.0.torch1.7.1-py3.8-linux-x86_64.egg, python3 -m k2.version, import k2; dir(k2) everything works fine. 

I removed the line "WORKDIR /workspace" and changed it to "git clone https://github.com/k2-fsa/k2.git /opt/k2 ". Then compile under /opt/k2 still exists the same error.

**Comment by csukuangfj** [comment]
You need to add that directory to the environment variable PYTHONPATH.

**Comment by yuekaizhang** [comment]
> You need to add that directory to the environment variable PYTHONPATH.

Thank you. It works.

**Comment by csukuangfj** [comment]
Maybe you can try the directory only up to the site-packages part and discard k2-xxx.
